Repository jina-ai/serve, pull requests merged in 2021-05, with the labels that each got.

#2372 ci(tag): update the vars about disk for deploying cloud.jina.ai
  .github/workflows/tag.yml
Labels: area/cicd, area/housekeeping, size/XS

#2377 feat: indexing works for hello-world
  jina/executors/__init__.py
  jina/executors/decorators.py
  jina/executors/helper.py
  jina/executors/indexers/dbms/__init__.py
  jina/executors/indexers/dbms/keyvalue.py
  jina/executors/indexers/dump.py
  jina/executors/indexers/keyvalue.py
  jina/helloworld/fashion/__init__.py
  jina/parsers/helloworld.py
  jina/resources/fashion/components.py
  jina/resources/fashion/helloworld.encoder.yml
  jina/resources/fashion/helloworld.flow.index.yml
  jina/resources/fashion/helloworld.indexer.yml
Labels: area/core, component/executor, component/resource, executor/indexer, executor/meta, size/L

#1958 test(docker): mocked unittests external calls
  tests/integration/hub_usage/test_hub_usage.py
  tests/integration/hub_usage/yaml/test-joint.yml
  tests/unit/docker/test_hub_build.py
  tests/unit/docker/test_hub_build_level.py
  tests/unit/docker/test_hub_list.py
  tests/unit/docker/test_hubio.py
  tests/unit/drivers/test_load_groundtruth_driver.py
Labels: area/testing, size/M

#2379 test: move helloworld test to system
  tests/integration/cache.py
  tests/integration/test_helloworld.py
  tests/system/fashion/test_fashion.py
Labels: area/testing, size/M

#2344 feat: change Pod context management
  jina/drivers/control.py
  jina/peapods/peas/__init__.py
  jina/peapods/pods/__init__.py
  jina/peapods/pods/compoundpod.py
  jina/peapods/runtimes/base.py
  jina/peapods/runtimes/jinad/__init__.py
  jina/peapods/runtimes/zmq/base.py
  jina/peapods/zmq/__init__.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  tests/integration/dump/__init__.py
  tests/integration/rolling_update/test_rolling_update.py
  tests/integration/rolling_update/yaml/custom.py
  tests/integration/rolling_update/yaml/mock_index_vector.yml
  tests/integration/rolling_update/yaml/simple_index_vector.yml
  tests/unit/peapods/pods/test_compound_pods.py
  tests/unit/peapods/pods/test_pods.py
  tests/unit/peapods/runtimes/asyncio/rest/test_models.py
Labels: area/core, area/network, area/testing, component/driver, component/peapod, component/proto, size/M

#2376 fix: broken link to extra deps documentation
  README.md
Labels: size/XS

#2384 test: add pytest-reraise to raise from thread
  extra-requirements.txt
  jina/flow/base.py
  jina/peapods/pods/compoundpod.py
  tests/distributed/test_remote_flow_dump_rolling_update_stress/test_dumb_dbms_remote.py
  tests/integration/dump/test_dump_dbms.py
  tests/integration/rolling_update/test_rolling_update.py
Labels: area/core, area/network, area/setup, area/testing, component/flow, component/peapod, size/S

#2385 fix: deactivate close handled by pea
  jina/peapods/peas/__init__.py
  jina/peapods/pods/__init__.py
  jina/peapods/pods/compoundpod.py
Labels: area/core, area/network, component/peapod, size/S

#2387 fix: comparison doc array
  jina/peapods/runtimes/zmq/zed.py
  tests/integration/v2_api/test_returns.py
Labels: area/core, area/network, area/testing, component/peapod, size/S

#2388 ci: add system path to get all test paths
  scripts/get-all-test-paths.sh
Labels: size/XS

#2366 feat: ranker trainer
  extra-requirements.txt
  jina/drivers/train/__init__.py
  jina/drivers/train/rank/__init__.py
  jina/executors/rankers/trainer.py
  tests/integration/ranker_training/__init__.py
  tests/integration/ranker_training/offline/__init__.py
  tests/integration/ranker_training/offline/flow_offline_search.yml
  tests/integration/ranker_training/offline/flow_offline_train.yml
  tests/integration/ranker_training/offline/test_offline_training.py
  tests/integration/ranker_training/offline/yaml/ranker.py
  tests/integration/ranker_training/offline/yaml/search.yml
  tests/integration/ranker_training/offline/yaml/train.yml
  tests/integration/ranker_training/offline/yaml/trainer.py
Labels: area/core, area/setup, area/testing, component/driver, component/executor, executor/ranker, size/M

#2399 fix: ensure same precision in dump
  jina/executors/indexers/dump.py
Labels: area/core, component/executor, executor/indexer, size/XS

#2404 fix: target_peapod behavior
  jina/clients/request/helper.py
  jina/peapods/runtimes/zmq/zed.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  jina/types/message/__init__.py
  jina/types/message/common.py
  tests/integration/v2_api/test_func_routing.py
Labels: area/core, area/network, area/testing, component/client, component/peapod, component/proto, component/type, size/M

#2403 feat: recover evaluation for fashion helloworld
  jina/helloworld/fashion/app.py
  jina/helloworld/fashion/demo.html
  jina/helloworld/fashion/executors.py
  jina/helloworld/fashion/flow.yml
  jina/helloworld/fashion/helper.py
  tests/system/fashion/test_fashion.py
  tests/unit/types/document/test_document.py
Labels: area/core, area/testing, size/M

#2409 test: add test rolling update
  extra-requirements.txt
  jina/executors/__init__.py
  jina/helloworld/fashion/executors.py
  jina/resources/executors.metas.default.yml
  tests/integration/rolling_update/__init__.py
  tests/integration/rolling_update/test_rolling_update.py
  tests/integration/rolling_update/yaml/custom.py
  tests/integration/rolling_update/yaml/simple_index_vector.yml
  tests/unit/executors/test_executor.py
  tests/unit/mwu-encoder/mwu_encoder.py
  tests/unit/mwu-encoder/mwu_encoder_upd.yml
  tests/unit/peapods/runtimes/container/test_container_runtime.py
Labels: area/core, area/setup, area/testing, component/executor, component/resource, executor/meta, size/M

#2405 refactor: remove unneeded decorators
  jina/executors/decorators.py
  tests/__init__.py
  tests/unit/executors/test_decorators.py
  tests/unit/test_helper.py
  tests/unit/types/document/test_document_traverse.py
Labels: 2.0, area/core, area/helper, area/testing, component/executor, executor/meta, size/XL

#2413 test: extra tests for hanging pods
  tests/integration/gateway_non_blocking/__init__.py
  tests/integration/inspect_pods_flow/__init__.py
  tests/integration/inspect_pods_flow/test_inspect_pods_flow.py
Labels: area/testing, size/S

#2347 test: compound pod sockets
  tests/unit/peapods/pods/test_compound_pods.py
Labels: area/testing, size/S

#2420 feat: attach endpoint to info message
  jina/peapods/runtimes/zmq/zed.py
Labels: area/core, area/network, component/peapod, size/S

#2421 feat: allow empty data req
  cli/autocomplete.py
  jina/clients/base.py
  jina/clients/mixin.py
  jina/clients/request/__init__.py
  jina/clients/request/asyncio.py
  jina/clients/request/helper.py
  jina/helloworld/fashion/flow.yml
  jina/parsers/client.py
  jina/peapods/runtimes/zmq/zed.py
  tests/unit/flow/test_asyncflow.py
  tests/unit/flow/test_flow.py
  tests/unit/peapods/runtimes/remote/jinad/yamls/flow-index.yaml
Labels: area/cli, area/core, area/network, area/testing, component/client, component/peapod, size/M

#2414 feat: add distributed rolling update tests to 2.0
  daemon/stores/flow.py
  jina/flow/base.py
  tests/distributed/test_remote_flow_dump_rolling_update/__init__.py
  tests/distributed/test_remote_flow_dump_rolling_update/docker-compose.yml
  tests/distributed/test_remote_flow_dump_rolling_update/flow_dbms.yml
  tests/distributed/test_remote_flow_dump_rolling_update/flow_query.yml
  tests/distributed/test_remote_flow_dump_rolling_update/pods/__init__.py
  tests/distributed/test_remote_flow_dump_rolling_update/pods/executors.py
  tests/distributed/test_remote_flow_dump_rolling_update/pods/indexer_dbms.yml
  tests/distributed/test_remote_flow_dump_rolling_update/pods/indexer_query.yml
  tests/distributed/test_remote_flow_dump_rolling_update/pods/merge_matches.yml
  tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
Labels: area/core, area/daemon, area/network, area/testing, component/flow, component/peapod, component/proto, size/M

#2422 refactor: runtime args
  .github/2.0/COOKBOOK-Document.md
  .github/2.0/COOKBOOK-Executor.md
  jina/executors/__init__.py
  jina/executors/decorators.py
  jina/executors/metas.py
  jina/jaml/__init__.py
  jina/jaml/parsers/executor/legacy.py
  jina/peapods/runtimes/zmq/zed.py
  tests/integration/rolling_update/test_rolling_update.py
  tests/unit/executors/test_executor.py
  tests/unit/executors/test_set_metas.py
  tests/unit/test_yamlparser.py
Labels: area/core, area/housekeeping, area/network, area/testing, component/executor, component/jaml, component/peapod, executor/meta, size/M

#2423 fix: fix test
  tests/distributed/test_remote_flow_dump_rolling_update/pods/executors.py
  tests/distributed/test_remote_flow_dump_rolling_update/pods/indexer_query.yml
  tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
  tests/integration/hub_usage/yaml/test-executor.yml
  tests/integration/hub_usage/yaml/test_executor.py
Labels: area/testing, size/S

#2425 fix: minor fix on ci, enums, docstrings
  .github/workflows/autocommit.yml
  .github/workflows/cd.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  README.md
  jina/__init__.py
  jina/enums.py
  jina/flow/asyncio.py
  jina/importer.py
  jina/parsers/peapods/runtimes/zed.py
  jina/peapods/runtimes/zmq/zed.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  tests/unit/flow/test_flow_skip.py
  tests/unit/test_importer.py
Labels: area/cicd, area/core, area/entrypoint, area/helper, area/housekeeping, area/network, area/testing, component/flow, component/peapod, component/proto, size/M

#2426 ci: detach hub submodule
  .github/workflows/cd.yml
  .github/workflows/ci-hub.yml
  .github/workflows/ci.yml
  .github/workflows/force-docker-build.yml
  .github/workflows/force-release.yml
  .github/workflows/latency-tracking.yml
  .github/workflows/release.yml
  .github/workflows/tag.yml
  tests/unit/docker/test_helper.py
  tests/unit/test_importer.py
Labels: area/cicd, area/housekeeping, size/S

#2427 refactor: traverse sequence
  README.md
  jina/types/arrays/traversable.py
  tests/unit/types/document/test_document_traverse.py
Labels: area/core, area/testing, component/type, size/S

#2428 fix: lazy request serialization
  .github/2.0/COOKBOOK-Document.md
  jina/executors/__init__.py
  jina/peapods/runtimes/asyncio/rest/models.py
  jina/peapods/runtimes/zmq/zed.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  jina/types/message/__init__.py
  tests/integration/v2_api/test_func_routing.py
  tests/unit/flow/test_asyncflow.py
  tests/unit/peapods/runtimes/asyncio/rest/test_models.py
  tests/unit/types/message/test_message.py
Labels: area/core, area/housekeeping, area/network, area/testing, component/executor, component/peapod, component/proto, component/type, executor/meta, size/M

#2416 feat: hello multimodal 2.0
  jina/clients/base.py
  jina/helloworld/multimodal/__init__.py
  jina/helloworld/multimodal/app.py
  jina/helloworld/multimodal/executors.py
  jina/helloworld/multimodal/flow-index.yml
  jina/helloworld/multimodal/flow-search.yml
  jina/helloworld/multimodal/helper.py
  tests/system/multimodal/test_multimodal.py
Labels: area/core, area/testing, component/client, size/L

#2432 Docs cookbook params
  .github/2.0/COOKBOOK-Executor.md
Labels: area/housekeeping, size/XS

#2424 feat: test nested matches of doc in a flow
  tests/integration/high_order_matches/test_document.py
Labels: area/testing, size/S

#2434 chore: update docstrings
  tests/integration/ranker_training/offline/test_offline_training.py
Labels: area/testing, size/XS

#2435 chore: fix broken links
  README.md
Labels: size/S

#2436 docs(1vs2): add extra reasons, rewrite existing
  .github/2.0/cookbooks/1vs2.md
  .github/2.0/flow-executor-doc.svg
  .github/2.0/lighter.svg
Labels: area/housekeeping, size/M

#2437 feat: switch gateway at runtime
  .github/2.0/cookbooks/Flow.md
  .github/2.0/empty-flow.svg
  .github/2.0/parallel-explain.svg
  .github/simple-flow0.svg
  .github/simple-flow1.svg
  .github/simple-flow2.png
  .github/simple-flow2.svg
  .github/simple-plot3.svg
  .github/simple-plot4.svg
  jina/enums.py
  jina/flow/base.py
  jina/helloworld/chatbot/app.py
  jina/helloworld/chatbot/executors.py
  tests/unit/flow/test_flow_change_gateway.py
Labels: area/core, area/helper, area/housekeeping, area/testing, component/flow, size/XL

#2441 minor improvement and typo fix to the cookbook of Executor
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2443 minor improvement and typo fix to the cookbook of Flow
  .github/2.0/cookbooks/Flow.md
Labels: area/housekeeping, size/XS

#2439 minor typo fix the cookbook of Document
  .github/2.0/cookbooks/Document.md
Labels: area/housekeeping, size/XS

#2452 fix: channel axis in normaliser
  jina/helloworld/multimodal/executors.py
Labels: area/core, size/XS

#2453 test(hub): remove pip installs
  tests/integration/hub_usage/dummyhub/Dockerfile
  tests/integration/hub_usage/dummyhub/requirements.txt
  tests/integration/hub_usage/dummyhub_abs/Dockerfile
  tests/integration/hub_usage/dummyhub_abs/requirements.txt
  tests/integration/hub_usage/dummyhub_pretrained/Dockerfile
  tests/integration/hub_usage/dummyhub_pretrained/requirements.txt
  tests/integration/hub_usage/dummyhub_slow/Dockerfile
  tests/integration/hub_usage/dummyhub_slow/requirements.txt
Labels: area/testing, size/S

#2455 test: add encoder/crafter test for multimodal helloworld
  tests/unit/helloworld/multimodal/test_executors.py
Labels: area/core, area/testing, size/S

#2454 fix: exclusivity doccontent
  .github/2.0/cookbooks/Document.md
  jina/types/document/__init__.py
  tests/unit/types/document/test_document.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/S

#2449 feat: example groupby Document
  .github/2.0/cookbooks/Document.md
Labels: area/housekeeping, size/S

#2457 refactor: remove jina hub submodule
  .gitmodules
Labels: size/XS

#2458 fix: default flow parser v1
  jina/jaml/parsers/__init__.py
Labels: area/core, component/jaml, size/XS

#2446 docs cookbook polish
  .github/2.0/cookbooks/CleanCode.md
  .github/2.0/cookbooks/Document.md
  .github/2.0/cookbooks/Executor.md
  .github/2.0/cookbooks/Flow.md
Labels: area/housekeeping, size/M

#2462 feat: add score value shortcut
  .github/2.0/cookbooks/Executor.md
  jina/types/arrays/chunk.py
  jina/types/document/__init__.py
  tests/unit/types/document/test_document.py
  tests/unit/types/score/test_score.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/S

#2460 feat(chatbot): increase the timeout_ready to 600000ms
  jina/helloworld/chatbot/app.py
Labels: area/core, size/XS

#2463 feat: allow build client from kwargs
  .github/2.0/cookbooks/Flow.md
  README.md
  jina/clients/__init__.py
  jina/clients/base.py
  jina/peapods/runtimes/asyncio/rest/app.py
  tests/unit/clients/python/test_client.py
Labels: area/core, area/housekeeping, area/network, area/testing, component/client, component/peapod, size/M

#2464 fix: check if data exist
  jina/helloworld/multimodal/app.py
Labels: area/core, size/XS

#2466 feat: add pythonic dict view for pb struct
  cli/autocomplete.py
  jina/clients/request/helper.py
  jina/helloworld/chatbot/app.py
  jina/parsers/hub/build.py
  jina/parsers/peapods/pea.py
  jina/peapods/runtimes/zmq/zed.py
  jina/types/document/__init__.py
  jina/types/request/__init__.py
  jina/types/struct.py
  tests/system/multimodal/test_multimodal.py
  tests/unit/peapods/runtimes/asyncio/rest/test_models.py
  tests/unit/proto/test_pb_struct_tags.py
  tests/unit/types/document/test_document.py
Labels: area/cli, area/core, area/network, area/testing, component/client, component/peapod, component/type, size/M

#2468 feat: add parser for changing REST JSON serialization
  jina/parsers/__init__.py
  jina/parsers/client.py
  jina/parsers/helper.py
  jina/parsers/peapods/runtimes/remote.py
  jina/peapods/pods/factory.py
  jina/peapods/runtimes/asyncio/rest/app.py
  tests/integration/issues/github_2103/test_search_attributes.py
Labels: area/core, area/network, area/testing, component/peapod, size/M

#2470 feat: add show_progress option to client cli
  README.md
  jina/__init__.py
  jina/clients/base.py
  jina/flow/base.py
  jina/parsers/client.py
Labels: area/core, area/entrypoint, area/helper, component/client, component/flow, size/S

#2451 fix: fixed hanging pod termination
  jina/peapods/zmq/__init__.py
  tests/integration/dump/__init__.py
  tests/integration/dump/test_dump_reload.py
Labels: area/core, area/network, area/testing, component/peapod, size/M

#2472 feat: add code snippets for using paddle in cookbooks
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2480 feat: add example for executor using tensorflow
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2482 refactor: move from_* helpers to types.document.generators
  .github/2.0/cookbooks/Document.md
  .github/2.0/cookbooks/Flow.md
  .github/2.0/implict-vs-explicit-service.svg
  README.md
  jina/helloworld/chatbot/app.py
  jina/helloworld/multimodal/app.py
  jina/types/arrays/document.py
  jina/types/document/generators.py
  tests/unit/clients/python/test_client.py
  tests/unit/clients/python/test_io.py
  tests/unit/clients/python/test_on_err.py
  tests/unit/flow/test_asyncflow.py
  tests/unit/flow/test_flow.py
  tests/unit/flow/test_flow_except.py
  tests/unit/flow/test_flow_yaml_parser.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/L

#2476 feat: add pytorch lightning snippet to cookbook
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2433 test: recreate sparse pipeline test for 2.0
  tests/integration/sparse_pipeline/.test_sparse_pipeline.py.swp
  tests/integration/sparse_pipeline/test_sparse_pipeline.py
Labels: area/housekeeping, area/testing, size/S

#2483 docs: add tags nested access in cookbook
  .github/2.0/cookbooks/Document.md
Labels: area/housekeeping, size/S

#2484 feat: Add description for tf executor example
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/XS

#2477 feat: add example of executor using fastai
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2475 feat: add example sklearn encoder with tfidf
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2474 feat: add mindspore to cookbook
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2478 feat: add pytorch to cookbook
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2488 fix: missing imports in code snippet
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/XS

#2465 refactor: meth update for document primitive type
  jina/types/document/__init__.py
  tests/unit/types/document/test_document.py
Labels: area/core, area/testing, component/type, size/M

#2487 fix(cookbook): fixing pytorch model inferences examples
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2490 docs(cookbooks): remove `with` property in minimum yml example
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/XS

#2485 feat: add test for store serialization
  daemon/models/base.py
  tests/daemon/unit/stores/test_basestore.py
Labels: area/daemon, area/testing, size/S

#2493 docs(what-neural-search): polish
  .github/2.0/neural-search.md
Labels: area/housekeeping, size/S

#2496 docs(cookbook): add missing ```
  .github/2.0/cookbooks/Document.md
Labels: area/housekeeping, size/XS

#2494 docs(cookbook): fix two typos in the executor part
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/XS

#2495 feat: add binary save load for DocumentArray
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/document.py
  tests/unit/types/arrays/test_documentarray.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/M

#2502 fix: delete from docarray by doc id
  jina/types/arrays/document.py
  tests/unit/types/arrays/test_documentarray.py
Labels: area/core, area/testing, component/type, size/S

#2498 feat(cookbook): add onnx_runtime snippet executor
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2506 fix: fail to import on armv8
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/force-docker-build.yml
  .github/workflows/tag.yml
  Dockerfiles/debianx.Dockerfile
  README.md
  RELEASE.md
  jina/__init__.py
  jina/clients/request/helper.py
  jina/executors/decorators.py
  jina/helloworld/fashion/app.py
  jina/types/arrays/document.py
  jina/types/document/generators.py
Labels: area/cicd, area/core, area/docker, area/entrypoint, area/helper, area/housekeeping, component/client, component/executor, component/type, executor/meta, size/S

#2501 test: add basic crud integration
  tests/__init__.py
  tests/integration/crud/__init__.py
  tests/integration/crud/simple/__init__.py
  tests/integration/crud/simple/flow.yml
  tests/integration/crud/simple/test_crud.py
Labels: area/testing, size/M

#2509 refactor(cli): remove read_only option
  .github/2.0/cookbooks/Executor.md
  cli/autocomplete.py
  jina/flow/base.py
  jina/flow/builder.py
  jina/parsers/__init__.py
  jina/parsers/peapods/runtimes/zed.py
Labels: area/cli, area/core, area/housekeeping, component/flow, size/S

#2511 feat: update 2.0 executor cookbook
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/S

#2512 fix: use update instead of MergeFrom
  jina/helloworld/multimodal/executors.py
Labels: area/core, size/XS

#2513 fix: update api in 2.0 cookbook
  .github/2.0/cookbooks/Document.md
Labels: area/housekeeping, size/XS

#2505 fix(daemon): handle empty requirements
  daemon/models/base.py
  daemon/models/workspaces.py
  daemon/stores/base.py
  daemon/stores/workspaces.py
  tests/daemon/unit/stores/test_workspacestore.py
Labels: area/daemon, area/testing, size/M

#2518 fix(daemon): create root workspace dir
  daemon/__init__.py
Labels: area/daemon, size/XS

#2519 test: added optimizer integration test back
  jina/optimizers/__init__.py
  jina/optimizers/flow_runner.py
  tests/integration/optimizers/__init__.py
  tests/integration/optimizers/data.jsonlines
  tests/integration/optimizers/flow.yml
  tests/integration/optimizers/optimizer_conf.yml
  tests/integration/optimizers/parameter.yml
  tests/integration/optimizers/pods/craft.yml
  tests/integration/optimizers/pods/dummy_crafter.py
  tests/integration/optimizers/pods/dummy_evaluate.py
  tests/integration/optimizers/pods/evaluate.yml
  tests/integration/optimizers/test_discovery.py
  tests/integration/optimizers/test_optimizer.py
Labels: area/core, area/testing, size/M

#2516 fix: fix flow show with replicas
  jina/flow/base.py
  jina/peapods/pods/__init__.py
  jina/peapods/pods/compound.py
Labels: area/core, area/network, component/flow, component/peapod, size/S

#2521 test: serialize crud and assert chunks
  tests/integration/crud/__init__.py
  tests/integration/crud/flow.yml
  tests/integration/crud/simple/__init__.py
  tests/integration/crud/test_crud.py
Labels: area/testing, size/S

#2523 feat: add ip range management
  daemon/dockerize.py
  daemon/models/containers.py
  daemon/models/workspaces.py
  daemon/stores/base.py
Labels: area/daemon, size/S

#2520 test: added groundtruths routing
  tests/integration/v2_api/test_func_routing.py
Labels: area/testing, size/S
