Repository jina-ai/serve, pull requests merged in 2021-07, with the labels that each got.

#2817 ci: ask devbot to do autocomplete and overload
  .github/workflows/ci-hub.yml
  .github/workflows/ci.yml
  .github/workflows/tag.yml
  README.md
  extra-requirements.txt
Labels: area/cicd, area/cli, area/core, area/housekeeping, area/setup, size/M

#2818 build: remove gevent deps
  .github/workflows/cd.yml
  .github/workflows/force-docker-build.yml
  .github/workflows/tag.yml
  Dockerfiles/debianx.Dockerfile
  README.md
  RELEASE.md
  extra-requirements.txt
  jina/flow/base.py
  jina/parsers/peapods/runtimes/remote.py
  jina/resources/extra-requirements.txt
  scripts/devbot.sh
  setup.py
Labels: area/cicd, area/core, area/docker, area/housekeeping, area/setup, component/flow, component/resource, size/M

#2812 refactor: add progress bar while push/pull
  jina/hubble/helper.py
  jina/hubble/hubio.py
  jina/hubble/progress_bar.py
Labels: area/core, size/M

#2819 refactor: remove unneeded func
  jina/peapods/pods/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#2824 fix(core): prevent peas from hanging on close
  jina/peapods/peas/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#2821 fix: container runtime on mac
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  cli/autocomplete.py
  daemon/api/dependencies.py
  jina/parsers/peapods/pea.py
  jina/peapods/networking.py
  jina/peapods/peas/__init__.py
  jina/peapods/runtimes/container/__init__.py
  tests/unit/peapods/pods/test_networking.py
Labels: area/cicd, area/cli, area/core, area/daemon, area/housekeeping, area/network, area/testing, component/peapod, size/S

#2830 fix(ci): add env vars for docker test to ci
  .github/workflows/ci.yml
Labels: area/cicd, area/housekeeping, size/S

#2828 fix(core): add sleep after terminate
  jina/peapods/peas/__init__.py
Labels: area/core, area/network, component/peapod, size/S

#2831 fix(logger): fix color log formatter
  jina/enums.py
  jina/logging/formatter.py
  jina/logging/logger.py
  jina/resources/logging.daemon.yml
  jina/resources/logging.default.yml
  jina/resources/logging.docker.yml
  jina/resources/logging.quiet.yml
  jina/resources/logging.remote.yml
  tests/unit/logging/test_logging.py
Labels: area/core, area/helper, area/testing, component/logging, component/resource, size/M

#2825 refactor: close from start error
  daemon/stores/partial.py
  jina/flow/base.py
  jina/helper.py
  jina/peapods/pods/__init__.py
Labels: area/core, area/daemon, area/helper, area/network, component/flow, component/peapod, size/S

#2833 refactor: refactor is ready
  jina/excepts.py
  jina/helper.py
  jina/peapods/peas/__init__.py
  jina/peapods/runtimes/base.py
  jina/peapods/runtimes/container/__init__.py
  jina/peapods/runtimes/gateway/grpc/__init__.py
  jina/peapods/runtimes/gateway/http/__init__.py
  jina/peapods/runtimes/gateway/websocket/__init__.py
  jina/peapods/runtimes/jinad/__init__.py
  jina/peapods/runtimes/zmq/base.py
  jina/peapods/runtimes/zmq/zed.py
  jina/peapods/zmq/__init__.py
  tests/unit/peapods/peas/test_pea.py
  tests/unit/peapods/runtimes/container/test_container_runtime.py
  tests/unit/peapods/zmq/test_dynamic_routing.py
  tests/unit/peapods/zmq/test_zmq_addr.py
Labels: area/core, area/helper, area/network, area/testing, component/peapod, size/M

#2835 test: remove extra pytest
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: area/core, area/setup, component/resource, size/XS

#2845 perf: optimize dockerfile layer cache
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/force-docker-build.yml
  .github/workflows/tag.yml
  Dockerfiles/debianx.Dockerfile
  daemon/Dockerfiles/devel.Dockerfile
  extra-requirements.txt
  jina/helper.py
  jina/hubble/hubio.py
  jina/resources/extra-requirements.txt
  jina/types/message/__init__.py
  setup.py
  tests/distributed/test_against_external_daemon/test_custom_container.py
  tests/distributed/test_against_external_daemon/test_remote_workspaces.py
  tests/distributed/test_against_external_daemon/test_topologies.py
  tests/distributed/test_against_external_daemon/test_topologies_docker.py
  tests/distributed/test_join_local_from_remote/docker-compose.yml
  tests/distributed/test_local_flow_local_remote_local/docker-compose.yml
  tests/distributed/test_local_flow_remote_local_remote/docker-compose.yml
  tests/distributed/test_simple_hub_pods/docker-compose.yml
Labels: area/cicd, area/core, area/daemon, area/docker, area/helper, area/housekeeping, area/setup, area/testing, component/flow, component/resource, component/type, size/L

#2847 fix: add readme snippet to CI
  README.md
  jina/clients/base/http.py
  jina/peapods/runtimes/gateway/http/models.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  jina/types/score/__init__.py
  jina/types/score/map.py
  tests/unit/test_readme.py
  tests/unit/types/document/test_document.py
  tests/unit/types/score/test_score_map.py
Labels: area/core, area/network, area/testing, component/client, component/peapod, component/proto, component/type, size/M

#2839 test: make unit tests success local
  tests/conftest.py
  tests/unit/clients/python/test_client.py
  tests/unit/flow/test_asyncflow.py
  tests/unit/flow/test_flow.py
  tests/unit/flow/test_flow_before_after.py
  tests/unit/flow/test_flow_change_gateway.py
  tests/unit/flow/test_flow_dynamic_routing.py
  tests/unit/flow/test_flow_example_face.py
  tests/unit/flow/test_flow_example_faiss.py
  tests/unit/flow/test_flow_except.py
  tests/unit/flow/test_flow_start_noblock.py
  tests/unit/flow/test_flow_yaml_parser.py
  tests/unit/flow/test_slow_executor_shutdown.py
  tests/unit/helloworld/multimodal/test_executors.py
  tests/unit/hubble/dummy_executor/__init__.py
  tests/unit/hubble/dummy_executor/exec.py
  tests/unit/logging/test_logging.py
  tests/unit/logging/yaml/file.yml
  tests/unit/peapods/peas/test_pea.py
  tests/unit/peapods/pods/test_compound_pods.py
  tests/unit/peapods/pods/test_pods.py
  tests/unit/peapods/runtimes/test_runtimes.py
  tests/unit/peapods/zmq/test_dynamic_routing.py
  tests/unit/test_cli.py
  tests/unit/test_echostream.py
  tests/unit/test_gateway.py
  tests/unit/test_loadbalance.py
  tests/unit/test_quant.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/document/test_document_traverse.py
  tests/unit/types/document/test_graph_document.py
  tests/unit/types/document/test_multimodal_document.py
  tests/unit/types/test_routing_graph.py
Labels: area/core, area/setup, area/testing, component/resource, size/M

#2738 refactor: change cancel runtime logic
  jina/peapods/peas/__init__.py
  jina/peapods/runtimes/container/__init__.py
  jina/peapods/runtimes/jinad/__init__.py
  jina/peapods/runtimes/zmq/asyncio.py
  jina/peapods/runtimes/zmq/base.py
  jina/peapods/runtimes/zmq/zed.py
  tests/unit/peapods/runtimes/container/test_container_runtime.py
  tests/unit/peapods/zmq/test_zmq_addr.py
Labels: area/core, area/network, area/testing, component/peapod, priority/important-longterm, size/M

#2850 chore: restructure daemon test directory
  .github/2.0/cookbooks/Daemon.md
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  daemon/parser.py
  daemon/stores/__init__.py
  tests/distributed/test_topologies/__init__.py
  tests/distributed/test_topologies/test_topologies.py
  tests/distributed/test_topologies_docker/__init__.py
  tests/distributed/test_topologies_docker/mwu-encoder/Dockerfile
  tests/distributed/test_topologies_docker/mwu-encoder/__init__.py
  tests/distributed/test_topologies_docker/mwu-encoder/mwu_encoder.py
  tests/distributed/test_topologies_docker/mwu-encoder/mwu_encoder.yml
  tests/distributed/test_topologies_docker/test_topologies_docker.py
  tests/distributed/test_workspaces/__init__.py
  tests/distributed/test_workspaces/custom_workspace_blocking/.jinad
  tests/distributed/test_workspaces/custom_workspace_no_run/.jinad
  tests/distributed/test_workspaces/docker-compose.yml
  tests/distributed/test_workspaces/flow_app_ws/.jinad
  tests/distributed/test_workspaces/flow_app_ws/app.py
  tests/distributed/test_workspaces/flow_app_ws/docker-compose.yml
  tests/distributed/test_workspaces/flow_app_ws/executors.py
  tests/distributed/test_workspaces/flow_app_ws/requirements.txt
  tests/distributed/test_workspaces/mwu_encoder.py
  tests/distributed/test_workspaces/mwu_encoder.yml
  tests/distributed/test_workspaces/tdb_indexer_ws/.jinad
  tests/distributed/test_workspaces/tdb_indexer_ws/mwu_encoder.yml
  tests/distributed/test_workspaces/tdb_indexer_ws/requirements.txt
  tests/distributed/test_workspaces/tdb_indexer_ws/tdb.yml
  tests/distributed/test_workspaces/tdb_indexer_ws/tdb_indexer.py
  tests/distributed/test_workspaces/test_custom_container.py
  tests/distributed/test_workspaces/test_remote_workspaces.py
  tests/distributed/test_workspaces/tf_encoder_ws/.jinad
  tests/distributed/test_workspaces/tf_encoder_ws/requirements.txt
  tests/distributed/test_workspaces/tf_encoder_ws/tf.yml
  tests/distributed/test_workspaces/tf_encoder_ws/tf_encoder.py
Labels: area/cicd, area/daemon, area/housekeeping, area/testing, size/S

#2851 fix: removed edge label from flow plot
  jina/flow/base.py
Labels: area/core, component/flow, size/XS

#2856 refactor: hubio module and hub cli
  cli/autocomplete.py
  extra-requirements.txt
  jina/hubble/helper.py
  jina/hubble/hubio.py
  jina/parsers/hubble/__init__.py
  jina/parsers/hubble/pull.py
  jina/parsers/hubble/push.py
  jina/peapods/peas/__init__.py
  jina/resources/extra-requirements.txt
  tests/unit/hubble/test_hubio.py
  tests/unit/parsers/hubble/test_pushpull.py
Labels: area/cli, area/core, area/network, area/setup, area/testing, component/peapod, component/resource, size/L

#2858 refactor(hubio): use rich to refactor cli ux
  cli/autocomplete.py
  jina/hubble/hubio.py
  jina/peapods/peas/__init__.py
Labels: area/cli, area/core, area/network, component/peapod, size/S

#2860 fix: fix the clustered UI when displaying alias
  jina/hubble/hubio.py
Labels: area/core, size/XS

#2843 fix(core): fix request/response missmatch while prefetching
  jina/peapods/runtimes/gateway/grpc/__init__.py
  jina/peapods/runtimes/gateway/http/app.py
  jina/peapods/runtimes/gateway/prefetch.py
  jina/peapods/runtimes/gateway/websocket/app.py
  tests/integration/concurrent_clients/__init__.py
  tests/integration/concurrent_clients/test_concurrent_clients.py
  tests/unit/peapods/runtimes/asyncio/rest/test_app.py
  tests/unit/peapods/runtimes/gateway/test_prefetch.py
Labels: area/core, area/jinaD, area/network, area/testing, component/peapod, size/M

#2760 fix(core): add complex test for routing list
  tests/unit/flow/test_flow.py
Labels: area/testing, size/S

#2875 fix: make hubble executor work in container
  jina/hubble/hubio.py
Labels: area/core, size/XS

#2859 feat: cache invalidator
  jina/helper.py
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  tests/unit/types/arrays/test_documentarray.py
Labels: area/cli, area/core, area/helper, area/testing, component/type, size/M

#2790 feat(hubble): ignore uuid and secret while push again
  extra-requirements.txt
  jina/hubble/helper.py
  jina/hubble/hubapi.py
  jina/hubble/hubio.py
  jina/resources/Python.gitignore
  jina/resources/extra-requirements.txt
  tests/unit/hubble/test_hubapi.py
Labels: area/core, area/setup, area/testing, component/resource, size/M

#2853 test: added remote local test
  jina/peapods/zmq/__init__.py
  tests/unit/peapods/zmq/test_dynamic_routing.py
  tests/unit/test_echostream.py
Labels: area/core, area/network, area/testing, component/peapod, size/S

#2869 fix: rolling update and hanging fix
  jina/peapods/peas/__init__.py
  jina/peapods/pods/__init__.py
  jina/peapods/pods/compound.py
  jina/peapods/runtimes/zmq/zed.py
  jina/peapods/zmq/__init__.py
  scripts/get-all-test-paths.sh
  tests/integration/rolling_update/test_rolling_update.py
  tests/integration/v2_api/test_docs_matrix_tail_pea.py
  tests/unit/peapods/peas/test_pea.py
  tests/unit/peapods/runtimes/test_runtimes.py
Labels: area/cicd, area/core, area/housekeeping, area/network, area/testing, component/peapod, size/M

#2880 docs(release): supplement image size info of standard
  RELEASE.md
Labels: size/XS

#2882 fix: corrected logging message
  jina/peapods/zmq/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#2877 feat: use alias in panel info
  jina/hubble/hubio.py
Labels: area/core, size/XS

#2874 feat: enabled latency-tracking CI job on push & PR
  .github/workflows/latency-tracking.yml
Labels: area/cicd, area/housekeeping, size/S

#2885 fix: fix index html
  jina/helloworld/multimodal/static/index.html
Labels: area/core, size/XS

#2890 fix: fix override with with parallel
  jina/executors/__init__.py
  tests/integration/override_config_params/container/test_override_config_params.py
  tests/integration/override_config_params/zed/test_override_config_params.py
Labels: area/core, area/testing, component/executor, executor/meta, size/S

#2892 fix(tests): remove hard coded ports in rolling update test
  tests/integration/rolling_update/test_rolling_update.py
Labels: area/testing, size/XS

#2891 refactor: hello multimodal refactor
  jina/helloworld/multimodal/flow-index.yml
  jina/helloworld/multimodal/flow-search.yml
  jina/helloworld/multimodal/my_executors.py
  jina/helloworld/multimodal/static/index.html
  tests/unit/helloworld/multimodal/test_executors.py
Labels: area/core, area/testing, size/M

#2893 docs: daemon cookbook
  .github/2.0/cookbooks/Daemon.md
  tests/distributed/helpers.py
  tests/distributed/test_workspaces/empty_flow.yml
  tests/distributed/test_workspaces/test_remote_workspaces.py
Labels: area/housekeeping, area/testing, size/M

#2897 chore: polish wording
  README.md
Labels: size/S

#2886 feat(logging): skip unnecessary log message constructions
  jina/logging/logger.py
  jina/peapods/runtimes/gateway/prefetch.py
  jina/peapods/runtimes/zmq/zed.py
Labels: area/core, area/network, component/logging, component/peapod, size/S

#2895 feat: raise exception when docker version is below 20.0.0
  jina/excepts.py
  jina/peapods/runtimes/container/__init__.py
  tests/unit/peapods/runtimes/container/test_container_runtime.py
Labels: area/core, area/helper, area/network, area/testing, component/peapod, size/S

#2871 fix(hubio): when error occurs, exit code should be set to non-zero
  jina/hubble/hubio.py
  tests/unit/hubble/test_hubio.py
Labels: area/core, area/entrypoint, area/helper, area/network, area/setup, area/testing, component/peapod, component/resource, component/type, size/S

#2898 fix: add examples fashion
  jina/helloworld/fashion/app.py
  jina/helloworld/fashion/helper.py
  jina/helloworld/fashion/my_executors.py
Labels: area/core, area/housekeeping, size/S

#2904 fix(hubio): raise exception when error occurs
  jina/hubble/hubio.py
Labels: area/core, size/XS

#2907 doc: declare cors in `Get Started` 's FLow
  README.md
Labels: size/XS

#2915 chore: disable the latency tracking
  .github/workflows/latency-tracking.yml
Labels: area/cicd, area/housekeeping, size/XS

#2911 fix: fix #2910
  jina/clients/mixin.py
  jina/peapods/runtimes/zmq/zed.py
  tests/integration/issues/github_2910/__init__.py
  tests/integration/issues/github_2910/test_flow.py
  tests/integration/v2_api/test_func_routing.py
Labels: area/core, area/network, area/testing, component/client, component/peapod, size/S

#2901 test: test flow.load_config with override_with on protocol
  tests/unit/flow/test_flow_yaml_parser.py
Labels: area/testing, size/S

#2866 feat(hubble): add filelock while installing executor from hubble
  extra-requirements.txt
  jina/hubble/hubapi.py
  jina/hubble/hubio.py
  jina/resources/extra-requirements.txt
Labels: area/core, area/setup, component/resource, size/S

#2916 test: timeout control adjusting for ci
  jina/parsers/peapods/runtimes/zmq.py
  tests/conftest.py
  tests/integration/rolling_update/test_rolling_update.py
  tests/integration/v2_api/test_docs_matrix_tail_pea.py
  tests/unit/clients/python/test_client.py
Labels: area/core, area/testing, size/S

#2902 fix: wait for server to stop in cancel
  jina/peapods/runtimes/gateway/http/__init__.py
  jina/peapods/runtimes/gateway/websocket/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#2922 refactor: small refactors
  jina/peapods/runtimes/gateway/http/__init__.py
  jina/peapods/runtimes/gateway/websocket/__init__.py
Labels: area/core, area/network, component/peapod, size/S

#2921 fix: remove unused import
  jina/peapods/runtimes/gateway/grpc/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#2926 feat: auto create workspace if not there
  jina/executors/__init__.py
  tests/unit/executors/test_executor.py
Labels: area/core, area/testing, component/executor, executor/meta, size/S

#2925 docs readme event banner
  .github/images/eah.svg
  README.md
Labels: area/housekeeping, size/S

#2928 fix: fix arguments passed
  jina/peapods/zmq/__init__.py
  tests/integration/external_pod/test_external_pod.py
Labels: area/core, area/network, area/testing, component/peapod, size/XS

#2931 ci: fix fluentd with jinad image
  Dockerfiles/debianx.Dockerfile
Labels: area/docker, size/XS

#2929 ci: adding rich to daemon reqs
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: area/core, area/setup, component/resource, size/S

#2932 doc: warn against simply run "jinad"
  .github/2.0/cookbooks/Daemon.md
Labels: area/housekeeping, size/XS

#2938 ci: add git to jinad docker image
  Dockerfiles/debianx.Dockerfile
Labels: area/docker, size/XS

#2924 tests: add tests for termination
  tests/integration/issues/hanging_termination/__init__.py
  tests/integration/issues/hanging_termination/test_hanging_termination.py
Labels: area/testing, size/M

#2940 fix(core): dont respond to cancel and idle
  jina/peapods/runtimes/zmq/zed.py
  tests/unit/peapods/peas/test_pea.py
Labels: area/core, area/network, area/testing, component/peapod, size/S

#2946 fix: add lz4, uvloop, filelock to daemon
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: area/core, area/setup, component/resource, size/S

#2941 refactor: small nicer refactor
  jina/peapods/runtimes/zmq/asyncio.py
Labels: area/core, area/network, component/peapod, size/S

#2947 fix: fix early pea shutdown logic
  jina/peapods/peas/__init__.py
  tests/unit/flow/test_flow_except.py
Labels: area/core, area/network, area/testing, component/peapod, size/S

#2935 feat: support offline executors
  jina/hubble/helper.py
  jina/hubble/hubio.py
  tests/conftest.py
  tests/unit/hubble/test_helper.py
  tests/unit/hubble/test_hubio.py
Labels: area/core, area/testing, size/M

#2951 chore: remove the meetup banner
  README.md
Labels: size/XS

#2933 feat: shipped latency tracking code in scripts
  .github/workflows/latency-tracking.yml
  .gitignore
  scripts/latency-tracking/README.md
  scripts/latency-tracking/app.py
  scripts/latency-tracking/requirements.txt
Labels: area/cicd, area/housekeeping, size/M

#2952 test: show external pod started with exec
  tests/integration/external_pod/test_external_pod.py
Labels: area/testing, size/M

#2945 fix(hubble): logging error message refering to jinahub uri
  jina/hubble/hubio.py
Labels: area/core, size/XS

#2948 feat(daemon): async interaction with children
  .github/2.0/cookbooks/Daemon.md
  daemon/__init__.py
  daemon/api/endpoints/flows.py
  daemon/api/endpoints/peas.py
  daemon/api/endpoints/pods.py
  daemon/helper.py
  daemon/models/containers.py
  daemon/stores/base.py
  daemon/stores/containers.py
  daemon/stores/flows.py
  daemon/stores/partial.py
  daemon/stores/peas.py
  daemon/stores/pods.py
  daemon/stores/workspaces.py
  jina/peapods/runtimes/jinad/client.py
  jina/peapods/zmq/__init__.py
  tests/conftest.py
  tests/daemon/unit/api/endpoints/test_logs.py
  tests/daemon/unit/stores/test_flowstore.py
  tests/daemon/unit/stores/test_partialstore.py
  tests/daemon/unit/stores/test_peapodstore.py
  tests/distributed/test_remote_flow_dump_rolling_update/docker-compose.yml
  tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
  tests/distributed/test_workspaces/delayed_flow/delayed_executor.py
  tests/distributed/test_workspaces/delayed_flow/delayed_executor.yml
  tests/distributed/test_workspaces/delayed_flow/delayed_flow.yml
  tests/distributed/test_workspaces/test_nonblocking.py
Labels: area/core, area/daemon, area/housekeeping, area/network, area/testing, component/peapod, size/L

#2960 docs(cookbook): add mac user hostname attention
  .github/2.0/cookbooks/Hubble.md
Labels: area/housekeeping, size/S

#2920 feat(hubble): upgrade the local executor if necessary
  jina/hubble/__init__.py
  jina/hubble/helper.py
  jina/hubble/hubapi.py
  jina/hubble/hubio.py
  jina/hubble/progress_bar.py
  tests/integration/hub_usage/test_hub_usage.py
  tests/unit/hubble/test_hubapi.py
  tests/unit/hubble/test_hubio.py
Labels: area/core, area/testing, size/L, type/feature-request

#2964 refactor(cli): rename override_metas/with to uses_metas/with
  .github/2.0/cookbooks/Hubble.md
  .github/pages/hello-world.md
  .github/workflows/latency-tracking.yml
  cli/autocomplete.py
  jina/flow/base.py
  jina/parsers/flow.py
  jina/parsers/peapods/pea.py
  jina/parsers/peapods/runtimes/zed.py
  jina/peapods/runtimes/zmq/zed.py
  scripts/inject-cli-as-overload.py
  tests/integration/override_config_params/container/flow.yml
  tests/integration/override_config_params/container/test_override_config_params.py
  tests/integration/override_config_params/zed/flow.yml
  tests/integration/override_config_params/zed/test_override_config_params.py
  tests/unit/peapods/runtimes/container/test_container_runtime.py
Labels: area/cicd, area/cli, area/core, area/housekeeping, area/network, area/testing, component/flow, component/peapod, size/L

#2965 fix: fix pydantic typo example
  jina/peapods/runtimes/gateway/http/models.py
Labels: area/core, area/network, component/peapod, size/XS

#2967 style(importer): improve styling and error message in importer
  jina/hubble/helper.py
  jina/hubble/hubapi.py
  jina/hubble/hubio.py
  jina/importer.py
Labels: area/core, area/helper, size/S

#2968 fix(ci): fix head commit ahead base commit
  .github/workflows/ci.yml
Labels: area/cicd, area/housekeeping, size/XS

#2971 fix(daemon): dockersock mounting for mac
  daemon/dockerize.py
  tests/daemon/unit/test_dockerize.py
Labels: area/daemon, area/testing, size/S

#2976 fix(types): allow setter Document.tags for StructView
  jina/types/document/__init__.py
  tests/integration/complex_tags/test_complex_tags.py
Labels: area/core, area/testing, component/type, size/S

#2981 fix(ci): disable latency tracking
  .github/workflows/latency-tracking.yml
Labels: area/cicd, area/housekeeping, size/XS

#2942 feat: add match function
  jina/types/arrays/document.py
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/testing, component/type, size/M

#2973 fix: fix setting extra host_connect_in
  jina/__init__.py
  jina/flow/base.py
  jina/peapods/networking.py
  jina/peapods/pods/__init__.py
  jina/peapods/zmq/__init__.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  jina/types/routing/table.py
  tests/distributed/test_local_flow_use_remote_executor/__init__.py
  tests/distributed/test_local_flow_use_remote_executor/docker-compose.yml
  tests/distributed/test_local_flow_use_remote_executor/test_integration.py
  tests/unit/types/test_routing_graph.py
Labels: area/core, area/entrypoint, area/helper, area/network, area/testing, component/flow, component/peapod, component/proto, component/type, size/M

#2980 fix: seek body file when computing _start
  jina/types/arrays/memmap.py
  tests/unit/types/arrays/test_memmap.py
Labels: area/core, area/testing, component/type, size/S

#2986 fix(cli): parse known args only and warn unknown
  cli/__init__.py
Labels: area/cli, size/S

#2983 docs(cookbook): add document creation clean code
  .github/2.0/cookbooks/CleanCode.md
Labels: area/housekeeping, size/S

#2984 refactor: update hello examples
  README.md
  jina/helloworld/chatbot/my_executors.py
  jina/helloworld/fashion/my_executors.py
  jina/helloworld/multimodal/my_executors.py
Labels: area/core, size/M

#2987 refactor(types): improving style and code quality of .match method
  jina/types/arrays/document.py
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/testing, component/type, size/S

#2989 feat(cli): add jina help cli for quick arg lookup
  cli/__init__.py
  cli/api.py
  cli/autocomplete.py
  cli/export.py
  cli/lookup.py
  jina/parsers/__init__.py
  tests/unit/test_cli.py
Labels: area/cli, area/core, area/testing, size/M

#2988 chore: adding new readme logo iteration animation
  .github/Jina Logo 420*140.gif
Labels: area/housekeeping, size/XS

#2995 fix: add match explanation in cookbook
  .github/2.0/cookbooks/Document.md
  .github/images/match_illustration_5.svg
Labels: area/housekeeping, size/S

#2996 feat: add meetup banner
  .github/images/meetup.svg
  README.md
Labels: area/housekeeping, size/S

#2969 feat: changed latency tracking Dockerfile location
  .github/workflows/latency-tracking.yml
Labels: area/cicd, area/housekeeping, size/S

#2993 fix: apply islice on iterator object of data in batch iterator
  jina/helper.py
  tests/integration/issues/github_2992/__init__.py
  tests/integration/issues/github_2992/test_flow.py
  tests/unit/test_helper.py
Labels: area/core, area/helper, area/testing, size/S

#2999 test: add test rolling update docker
  jina/peapods/pods/compound.py
  tests/integration/rolling_update/Dockerfile
  tests/integration/rolling_update/test_rolling_update.py
Labels: area/core, area/network, area/testing, component/peapod, size/S

#2997 feat: find method for DocumentArray
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_search_ops.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/M

#3004 fix: add missing tests find method
  tests/unit/types/arrays/test_search_ops.py
Labels: area/testing, size/S

#3005 fix(types): clear matches before adding
  jina/helloworld/chatbot/my_executors.py
  jina/helloworld/fashion/my_executors.py
  jina/types/arrays/neural_ops.py
  tests/system/fashion/test_fashion.py
Labels: area/core, area/testing, component/type, size/S

#3006 feat(flow): add uses on flow plot
  jina/flow/base.py
Labels: area/core, component/flow, size/S

#3007 ci: cancel prev runs for tests
  .github/workflows/ci.yml
  .github/workflows/latency-tracking.yml
Labels: area/cicd, area/housekeeping, size/S

#3003 feat: add sample method to document array
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/arrays/test_memmap.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/S

#3009 fix(hubble): more informed logging for fetch_meta
  jina/hubble/hubio.py
Labels: area/core, size/XS

#3016 refactor(types): move common math function to jina.math module
  .github/2.0/cookbooks/Document.md
  .github/labeler.yml
  jina/math/__init__.py
  jina/math/distance.py
  jina/math/helper.py
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/M

#3018 fix(cli): fix lookup on hidden args
  .github/images/meetup.svg
  cli/export.py
  cli/lookup.py
Labels: area/cli, size/S

#3019 feat(types): allow scipy metric in match and add minmax normalization
  .github/2.0/cookbooks/Document.md
  README.md
  jina/helloworld/chatbot/my_executors.py
  jina/helloworld/fashion/my_executors.py
  jina/helloworld/multimodal/my_executors.py
  jina/math/helper.py
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/housekeeping, area/testing, component/math, component/type, size/M

#2953 fix(importer): add custom sys meta path finder
  jina/importer.py
  jina/jaml/__init__.py
Labels: area/core, area/helper, component/jaml, size/S

#3021 feat: add shuffle to documentarray
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/arrays/test_memmap.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/S

#3008 Updated README.md
  README.md
Labels: size/XS

#3020 fix: latency tracking long running issue
  .github/workflows/latency-tracking.yml
  scripts/latency-tracking/app.py
Labels: area/cicd, area/housekeeping, size/S

#2994 feat(daemon): python client
  .github/2.0/cookbooks/Daemon.md
  daemon/__init__.py
  daemon/api/dependencies.py
  daemon/api/endpoints/flows.py
  daemon/api/endpoints/logs.py
  daemon/api/endpoints/partial/flow.py
  daemon/api/endpoints/partial/pea.py
  daemon/api/endpoints/partial/pod.py
  daemon/api/endpoints/peas.py
  daemon/api/endpoints/pods.py
  daemon/api/endpoints/workspaces.py
  daemon/clients/__init__.py
  daemon/clients/base.py
  daemon/clients/flows.py
  daemon/clients/mixin.py
  daemon/clients/peas.py
  daemon/clients/pods.py
  daemon/clients/workspaces.py
  daemon/dockerize.py
  daemon/excepts.py
  daemon/helper.py
  daemon/models/id.py
  daemon/parser.py
  daemon/stores/__init__.py
  daemon/stores/base.py
  daemon/stores/containers.py
  daemon/stores/flows.py
  daemon/stores/partial.py
  daemon/stores/peas.py
  daemon/tasks.py
  jina/excepts.py
  jina/helper.py
  jina/peapods/runtimes/jinad/__init__.py
  jina/peapods/runtimes/jinad/client.py
  tests/daemon/unit/api/endpoints/test_logs.py
  tests/daemon/unit/clients/test_clients.py
  tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
  tests/distributed/test_workspaces/flow_app_ws/app.py
  tests/distributed/test_workspaces/flow_app_ws/docker-compose.yml
  tests/distributed/test_workspaces/flow_app_ws/executors.py
  tests/distributed/test_workspaces/flow_app_ws/requirements.txt
  tests/distributed/test_workspaces/sklearn_encoder_ws/.jinad
  tests/distributed/test_workspaces/sklearn_encoder_ws/encoder.py
  tests/distributed/test_workspaces/sklearn_encoder_ws/requirements.txt
  tests/distributed/test_workspaces/sklearn_encoder_ws/sklearn.yml
  tests/distributed/test_workspaces/test_custom_container.py
  tests/distributed/test_workspaces/test_exceptions.py
  tests/distributed/test_workspaces/test_nonblocking.py
  tests/distributed/test_workspaces/test_remote_workspaces.py
  tests/distributed/test_workspaces/tf_encoder_ws/requirements.txt
  tests/distributed/test_workspaces/tf_encoder_ws/tf.yml
  tests/distributed/test_workspaces/wrong_flow.yml
  tests/unit/peapods/runtimes/remote/jinad/test_api.py
Labels: area/core, area/daemon, area/helper, area/housekeeping, area/network, area/testing, component/peapod, size/XL

#3001 feat: enabled benchmarking into ci
  .github/workflows/tag.yml
Labels: area/cicd, area/housekeeping, size/S

#3028 docs: remote executor usage
  .github/2.0/cookbooks/Daemon.md
Labels: area/housekeeping, size/XS

#3023 refactor(parser): clarify gpu argument description
  jina/flow/base.py
  jina/parsers/peapods/runtimes/container.py
Labels: area/core, component/flow, size/XS

#3031 feat(hub): add new command to jina hub CLI
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  cli/__init__.py
  cli/autocomplete.py
  cli/export.py
  jina/hubble/hubio.py
  jina/parsers/hubble/__init__.py
  jina/resources/executor-template/README.md
  jina/resources/executor-template/config.yml
  jina/resources/executor-template/executor.py
  jina/resources/executor-template/manifest.yml
  jina/resources/executor-template/requirements.txt
  scripts/black.sh
  scripts/docstrings_lint.sh
Labels: area/cicd, area/cli, area/core, area/housekeeping, component/resource, size/M

#3033 test(daemon): py module
  daemon/Dockerfiles/default.Dockerfile
  daemon/clients/peas.py
  daemon/helper.py
  daemon/stores/containers.py
  jina/peapods/runtimes/jinad/__init__.py
  tests/daemon/unit/clients/test_clients.py
  tests/distributed/test_workspaces/test_exceptions.py
  tests/distributed/test_workspaces/test_remote_workspaces.py
Labels: area/core, area/daemon, area/network, area/testing, component/peapod, size/S

#3032 fix: fashion hello world fix
  jina/helloworld/fashion/helper.py
Labels: area/core, size/S

#3035 ci: remove unnecessary dev bot token
  .github/workflows/ci.yml
  .github/workflows/label-pr.yml
Labels: area/cicd, area/housekeeping, size/XS

#3039 fix(hub): fix typo base image name
  jina/resources/executor-template/Dockerfile
Labels: area/core, component/resource, size/XS

#3038 refactor(document): do not hash content if copy is true
  jina/types/document/__init__.py
Labels: area/core, component/type, size/XS

#3040 fix: match with same documents
  jina/types/arrays/neural_ops.py
  jina/types/document/__init__.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/testing, component/type, size/S

#3042 ci: default token for cancel workflow
  .github/workflows/ci.yml
  .github/workflows/latency-tracking.yml
Labels: area/cicd, area/housekeeping, size/XS

#3046 fix(http): fix pydantic models
  jina/peapods/runtimes/gateway/http/models.py
Labels: area/core, area/network, component/peapod, size/S

#3050 fix(helloworld): fix doc content to 1d array
  jina/helloworld/fashion/my_executors.py
  jina/helloworld/multimodal/my_executors.py
  jina/types/document/converters.py
Labels: area/core, component/type, size/S

#3045 refactor: try to speed up update content hash
  jina/types/document/__init__.py
  jina/types/document/multimodal.py
  tests/unit/types/document/test_document.py
Labels: area/core, area/testing, component/type, size/M

#3015 feat: pca algorithm
  extra-requirements.txt
  jina/math/dimensionality_reduction.py
  jina/resources/extra-requirements.txt
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/setup, area/testing, component/math, component/resource, component/type, size/M

#3056 perf(types): remove redundant copy in match function
  jina/types/arrays/document.py
  jina/types/arrays/match.py
  jina/types/arrays/neural_ops.py
  jina/types/document/__init__.py
Labels: area/core, component/type, size/S

#3058 refactor(proto): remove content_hash from builtin proto
  jina/clients/base/websocket.py
  jina/clients/request/helper.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  jina/proto/serializer.py
  jina/types/arrays/chunk.py
  jina/types/arrays/document.py
  jina/types/arrays/match.py
  jina/types/document/__init__.py
  jina/types/document/multimodal.py
  jina/types/message/__init__.py
  jina/types/mixin.py
  jina/types/request/__init__.py
  tests/__init__.py
  tests/distributed/test_local_flow_local_remote_local/test_integration.py
  tests/distributed/test_local_flow_remote_local_remote/test_integration.py
  tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
  tests/integration/issues/hanging_termination/test_hanging_termination.py
  tests/unit/flow/test_asyncflow.py
  tests/unit/peapods/runtimes/asyncio/rest/test_models.py
  tests/unit/types/arrays/test_chunkarray.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/arrays/test_matcharray.py
  tests/unit/types/document/test_document.py
  tests/unit/types/document/test_helper.py
  tests/unit/types/document/test_multimodal_document.py
Labels: area/core, area/network, area/testing, component/client, component/proto, component/type, size/M
