Repository jina-ai/serve, pull requests merged in 2021-08, with the labels that each got.

#3059 feat(types): improve usability of visualize function
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/testing, component/type, size/S

#3060 perf(types): remove cache_invalidator in DA for better performance
  .github/release-template.ejs
  jina/types/arrays/document.py
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_documentarray.py
Labels: area/core, area/housekeeping, area/testing, component/type, size/M

#3062 feat: add env JINA_MP_START_METHOD for changing mp start_method
  CONTRIBUTING.md
  jina/__init__.py
  jina/types/arrays/neural_ops.py
  tests/__init__.py
  tests/conftest.py
  tests/unit/test_cli.py
Labels: area/core, area/entrypoint, area/helper, area/testing, component/type, size/S

#3063 feat(types): add tsne algorithm to visualization
  jina/types/arrays/neural_ops.py
Labels: area/core, component/type, size/S

#3064 perf(types): remove unnecessary DA building in get_attributes
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  tests/unit/types/arrays/test_memmap.py
Labels: area/core, area/testing, component/type, size/S

#3065 fix(math): fix minmax normalize to row-wise normalization
  jina/math/helper.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/testing, component/math, size/S

#3073 fix: fix 0 sparse array
  jina/types/ndarray/dense/numpy.py
  tests/unit/types/document/test_document.py
Labels: area/core, area/testing, component/type, size/S

#3074 fix: fix plot
  jina/flow/base.py
Labels: area/core, component/flow, size/XS

#3078 fix(setup): fix missing wheel dependencies in setup.py
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  extra-requirements.txt
  jina/resources/extra-requirements.txt
  setup.py
Labels: area/cicd, area/core, area/housekeeping, area/setup, component/resource, size/M

#3084 fix(init): bring back default fork mp start method on macos
  jina/__init__.py
Labels: area/core, area/entrypoint, area/helper, size/S

#3069 refactor: change bind to all inbound
  jina/peapods/runtimes/gateway/grpc/__init__.py
  jina/peapods/runtimes/gateway/http/__init__.py
  jina/peapods/runtimes/gateway/websocket/__init__.py
Labels: area/core, area/network, component/peapod, size/S

#3051 feat: connect to pred config
  cli/autocomplete.py
  jina/flow/base.py
  jina/parsers/__init__.py
  jina/parsers/peapods/pod.py
  jina/parsers/peapods/runtimes/zed.py
  jina/peapods/pods/__init__.py
  tests/distributed/test_local_flow_use_remote_executor/docker-compose-parallel.yml
  tests/distributed/test_local_flow_use_remote_executor/docker-compose.yml
  tests/distributed/test_local_flow_use_remote_executor/test_integration.py
  tests/integration/external_pod/test_external_pod.py
  tests/unit/flow/test_flow.py
Labels: area/cli, area/core, area/network, area/testing, component/flow, component/peapod, size/S

#3092 feat(executor): add uses-requests cli to override requests in Executor
  cli/autocomplete.py
  jina/flow/base.py
  jina/jaml/__init__.py
  jina/parsers/peapods/runtimes/zed.py
  jina/peapods/runtimes/zmq/zed.py
  tests/integration/override_config_params/zed/test_override_config_params.py
Labels: area/cli, area/core, area/network, area/testing, component/flow, component/jaml, component/peapod, size/M

#2985 feat: change default entrypoint and allow runtimes in main process
  cli/api.py
  jina/peapods/peas/__init__.py
  jina/peapods/runtimes/base.py
  jina/peapods/runtimes/container/__init__.py
  jina/peapods/runtimes/gateway/grpc/__init__.py
  jina/peapods/runtimes/gateway/http/__init__.py
  jina/peapods/runtimes/gateway/websocket/__init__.py
  jina/peapods/runtimes/jinad/__init__.py
  jina/peapods/runtimes/zmq/asyncio.py
  jina/peapods/runtimes/zmq/base.py
  jina/peapods/runtimes/zmq/zed.py
  jina/peapods/zmq/__init__.py
  tests/integration/runtime_signal_handling/__init__.py
  tests/integration/runtime_signal_handling/test_runtime_captures_signals.py
  tests/unit/peapods/peas/test_pea.py
  tests/unit/peapods/runtimes/test_runtimes.py
  tests/unit/peapods/zmq/test_dynamic_routing.py
Labels: area/cli, area/core, area/network, area/testing, component/peapod, size/L

#3097 fix: add sparse support
  .github/2.0/cookbooks/Document.md
  jina/math/distance.py
  jina/math/helper.py
  jina/types/arrays/neural_ops.py
  tests/unit/math/__init__.py
  tests/unit/math/test_distance.py
  tests/unit/math/test_helper.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, area/housekeeping, area/testing, component/math, component/type, size/L

#3102 fix: delete and list workspaces
  daemon/clients/base.py
  daemon/stores/workspaces.py
  tests/distributed/test_workspaces/test_remote_workspaces.py
Labels: area/daemon, area/testing, size/S

#3111 feat(daemon): rolling update via client
  daemon/api/endpoints/flows.py
  daemon/api/endpoints/pods.py
  daemon/clients/flows.py
  daemon/clients/pods.py
  daemon/clients/workspaces.py
  daemon/helper.py
  daemon/stores/containers.py
  daemon/stores/flows.py
  daemon/stores/partial.py
  daemon/stores/peas.py
  tests/distributed/test_remote_flow_dump_rolling_update/test_dump_dbms_remote.py
Labels: size/M, area/testing, area/daemon

#3105 feat: add data request handler
  cli/api.py
  jina/peapods/runtimes/request_handlers/__init__.py
  jina/peapods/runtimes/request_handlers/data_request_handler.py
  jina/peapods/runtimes/zmq/zed.py
  jina/peapods/zmq/__init__.py
  tests/unit/peapods/runtimes/request_handlers/__init__.py
  tests/unit/peapods/runtimes/request_handlers/test_data_request_handlers.py
Labels: size/L, area/core, area/testing, area/network, component/peapod, area/cli

#3115 Update README.md
  README.md
Labels: size/XS

#3117 refactor: remove attribute
  jina/peapods/runtimes/zmq/zed.py
Labels: area/core, area/network, component/peapod, size/XS

#3112 refactor: improve document update method
  jina/types/document/__init__.py
Labels: area/core, size/S, component/type

#3116 feat: supporting jina hub push --tag and --docker-file
  .github/2.0/cookbooks/Hub.md
  .github/2.0/cookbooks/Hubble.md
  cli/autocomplete.py
  jina/hubble/hubio.py
  jina/parsers/hubble/push.py
  tests/unit/parsers/hubble/test_pushpull.py
Labels: size/M, area/housekeeping, area/core, area/testing, area/cli

#3104 feat(hubble): push/pull rich logging
  jina/hubble/hubio.py
  tests/unit/hubble/test_hubio.py
Labels: size/M, area/core, area/testing

#3113 feat: match with batching capability
  jina/math/helper.py
  jina/types/arrays/neural_ops.py
  tests/unit/math/test_helper.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: size/M, area/core, area/testing, component/type, component/math

#3126 style(dam): improve styling and imports for DAM
  jina/types/arrays/bpm.py
Labels: area/core, size/S, component/type

#3128 perf(dam): cache mmap object targeting #3002
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/memmap.py
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_memmap.py
Labels: area/housekeeping, area/core, size/S, area/testing, component/type

#3131 fix(hubio): more meaningful exception when docker not running
  jina/hubble/hubio.py
Labels: area/core, size/S

#3002 feat: unify da dam interface
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/abstract.py
  jina/types/arrays/bpm.py
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  jina/types/arrays/search_ops.py
  jina/types/document/__init__.py
  jina/types/document/helper.py
  tests/unit/types/arrays/test_buffer.py
  tests/unit/types/arrays/test_memmap.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/housekeeping, area/core, area/testing, size/XL, component/type

#3133 Add black logo
  docs/_static/logo-black.svg
Labels: size/S, area/docs

#3135 docs: add black logo
  docs/_static/logo-black.svg
Labels: size/S, area/docs

#3098 docs: update cookbooks #138
  .github/2.0/chain-flow.svg
  .github/2.0/cookbooks/Daemon.md
  .github/2.0/cookbooks/Document.md
  .github/2.0/cookbooks/Executor.md
  .github/2.0/cookbooks/Flow.md
  .github/2.0/cookbooks/Hub.md
  .github/2.0/cookbooks/Math.md
  .github/2.0/cookbooks/Serving.md
  .github/2.0/document-array-visualize.png
  .github/2.0/empty-flow.svg
  .github/2.0/jina-hub-new.gif
  .github/2.0/parallel-explain.svg
  .github/simple-plot3.svg
  .github/simple-plot4.svg
  jina/types/document/graph.py
Labels: area/housekeeping, area/core, size/XL, component/type

#3136 fix(hubble): docker pull progressbar
  jina/hubble/helper.py
  jina/hubble/hubio.py
  tests/unit/hubble/docker_pull.logs
  tests/unit/hubble/test_hubio.py
Labels: size/L, area/core, area/testing

#3132 test: refactor test
  tests/unit/types/arrays/test_neural_ops.py
Labels: size/M, area/testing

#3101 docs(Executor.md): Minor typos
  .github/2.0/cookbooks/Executor.md
Labels: area/housekeeping, size/XS

#3145 refactor(setup): make standard deps as the default deps
  .github/workflows/force-docker-build.yml
  Dockerfiles/debianx.Dockerfile
  README.md
  RELEASE.md
  setup.py
Labels: size/S, area/setup

#3146 docs: update dam chapter and add uses_with , uses_metas , uses_requests to Flow.md
  .github/2.0/cookbooks/Document.md
  .github/2.0/cookbooks/Flow.md
Labels: size/M, area/housekeeping

#3125 docs(hub): add description about the tag of hub
  .github/2.0/cookbooks/Hub.md
Labels: area/housekeeping, size/S

#3122 docs: daemon in readme
  .github/2.0/cookbooks/Daemon.md
  README.md
Labels: size/M, area/housekeeping

#3150 fix: allow more versions of dgl
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: size/XS, area/setup

#3148 refactor: no copy on append
  jina/types/arrays/chunk.py
  jina/types/arrays/match.py
  jina/types/arrays/neural_ops.py
Labels: area/core, size/S, component/type

#3151 refactor: remove dict keys creation
  jina/types/document/__init__.py
Labels: area/core, size/XS, component/type

#3152 fix: catch RuntimeError on signal handler set
  jina/peapods/runtimes/zmq/asyncio.py
Labels: area/core, area/network, component/peapod, size/XS

#3153 fix: fix error message test
  jina/peapods/zmq/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#3130 perf: cache get attribute embedding
  jina/types/arrays/memmap.py
  tests/unit/types/arrays/test_memmap.py
Labels: size/M, area/core, area/testing, component/type

#3147 test: increase hub test coverage
  jina/hubble/helper.py
  tests/unit/hubble/Dockerfile
  tests/unit/hubble/dummy_executor.tar
  tests/unit/hubble/dummy_executor.tar.gz
  tests/unit/hubble/dummy_executor.zip
  tests/unit/hubble/test_helper.py
  tests/unit/hubble/test_hubapi.py
  tests/unit/hubble/test_hubio.py
Labels: size/M, area/core, area/testing

#3137 docs: add links to tutorials in README
  README.md
Labels: size/XS

#3158 refactor: remove unused imports
  jina/types/arrays/neural_ops.py
Labels: area/core, size/XS, component/type

#3157 feat: add efficient access to embeddings
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: size/M, area/housekeeping, area/core, area/testing, component/type

#3162 ci: inject Document overload during CI
  jina/types/document/__init__.py
  scripts/devbot.sh
  scripts/inject-document-props-as-overload.py
Labels: size/M, area/core, component/type

#3164 fix: errorlog from partiald
  .github/2.0/cookbooks/Daemon.md
  daemon/excepts.py
  daemon/stores/containers.py
Labels: area/housekeeping, size/S, area/daemon

#3129 feat: grpc for requests
  cli/api.py
  cli/autocomplete.py
  jina/flow/base.py
  jina/parsers/peapods/runtimes/zed.py
  jina/peapods/grpc/__init__.py
  jina/peapods/peas/__init__.py
  jina/peapods/runtimes/__init__.py
  jina/peapods/runtimes/gateway/grpc/__init__.py
  jina/peapods/runtimes/gateway/prefetch.py
  jina/peapods/runtimes/grpc/__init__.py
  jina/peapods/runtimes/jinad/__init__.py
  jina/proto/jina.proto
  jina/proto/jina_pb2.py
  jina/proto/jina_pb2_grpc.py
  jina/proto/serializer.py
  jina/types/message/__init__.py
  tests/unit/flow/test_flow_dynamic_routing.py
  tests/unit/peapods/grpc/__init__.py
  tests/unit/peapods/grpc/test_grpclet.py
  tests/unit/peapods/runtimes/gateway/test_prefetch.py
  tests/unit/peapods/runtimes/grpc/__init__.py
  tests/unit/peapods/runtimes/grpc/test_grpc_data_runtime.py
Labels: area/core, area/testing, area/network, component/peapod, size/XL, component/flow, component/proto, component/type, area/cli

#3144 fix: executor point to pea again
  cli/api.py
  cli/autocomplete.py
  jina/parsers/__init__.py
  tests/integration/issues/github_3124/Dockerfile
  tests/integration/issues/github_3124/__init__.py
  tests/integration/issues/github_3124/test_cli_executor.py
Labels: size/M, area/core, area/testing, area/cli

#3167 feat: add split prepare for trainer
  .github/2.0/cookbooks/Document.md
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/arrays/test_memmap.py
Labels: area/housekeeping, area/core, size/S, area/testing, component/type

#3173 fix(math): bound cosine and minmax norm and fix divide-zero
  jina/helloworld/fashion/my_executors.py
  jina/math/distance.py
  jina/math/helper.py
  jina/types/arrays/neural_ops.py
  tests/unit/math/test_helper.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: area/core, size/S, area/testing, component/type, component/math

#3175 fix(daemon): hub cache env var
  daemon/__init__.py
  daemon/dockerize.py
Labels: size/S, area/daemon

#3176 fix(math): normalization after topk with original minmax value
  jina/math/helper.py
  jina/types/arrays/neural_ops.py
Labels: area/core, size/S, component/type, component/math

#3177 refactor: remove imports
  jina/peapods/zmq/__init__.py
Labels: area/core, area/network, component/peapod, size/XS

#3047 chore: merge latency tracking repo
  .github/workflows/latency-tracking.yml
  scripts/latency-tracking/Dockerfile
  scripts/latency-tracking/README.md
  scripts/latency-tracking/app.py
  scripts/latency-tracking/merge_outputs.py
  scripts/latency-tracking/ppstat.py
  scripts/latency-tracking/track.sh
Labels: size/M, area/housekeeping, area/cicd

#3180 chore: merge demo dependencies
  .github/pages/hello-world.md
  README.md
  extra-requirements.txt
  jina/parsers/helloworld.py
  jina/resources/extra-requirements.txt
Labels: area/housekeeping, area/core, size/S, component/resource, area/setup

#3179 fix: traverse chunk match
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  jina/types/arrays/traversable.py
  tests/unit/types/document/test_document_traverse.py
Labels: area/core, size/S, area/testing, component/type

#3183 fix(types): fix document id type hint
  .github/workflows/ci.yml
  jina/types/document/__init__.py
  scripts/inject-document-props-as-overload.py
Labels: area/housekeeping, area/core, size/S, area/cicd, component/type

#3184 perf: use embeddings property in cache
  jina/types/arrays/memmap.py
  jina/types/arrays/neural_ops.py
Labels: area/core, size/S, component/type

#3190 feat: add setter to embeddings
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  jina/types/arrays/neural_ops.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/arrays/test_memmap.py
  tests/unit/types/arrays/test_neural_ops.py
Labels: size/M, area/core, area/testing, component/type

#3189 feat: enabled workflows for external contributors
  .github/workflows/cla.yml
  .github/workflows/commit-lint.yml
  .github/workflows/hacktoberfest.yml
  .github/workflows/label-pr.yml
Labels: area/housekeeping, area/cicd, size/XS

#3196 refactor(cli): 💥 change zed_runtime to executor --native
  .github/release-template.ejs
  cli/api.py
  cli/autocomplete.py
  jina/flow/base.py
  jina/parsers/__init__.py
  jina/parsers/peapods/pea.py
  jina/parsers/peapods/runtimes/zed.py
  tests/integration/issues/github_3124/test_cli_executor.py
  tests/integration/runtime_signal_handling/test_runtime_captures_signals.py
Labels: size/M, area/housekeeping, area/core, area/testing, component/flow, area/cli

#3172 feat: unknown args loggin
  cli/__init__.py
  jina/flow/base.py
  jina/helper.py
  jina/jaml/parsers/flow/v1.py
  jina/parsers/helper.py
  tests/unit/parsers/test_warnings.py
Labels: size/M, area/core, area/helper, area/testing, component/flow, area/cli, component/jaml

#3198 feat: blobs property
  jina/types/arrays/document.py
  jina/types/arrays/memmap.py
  tests/unit/types/arrays/test_documentarray.py
  tests/unit/types/arrays/test_memmap.py
Labels: size/M, area/core, area/testing, component/type

#3203 fix(setup): add core deps to perf deps
  setup.py
Labels: size/XS, area/setup

#3200 feat: pass native in container runtime docker
  jina/peapods/runtimes/container/__init__.py
  tests/unit/peapods/runtimes/container/test_container_runtime.py
Labels: area/core, size/S, area/testing, area/network, component/peapod

#3207 perf(types): remove warning logic in binary doc construction
  jina/types/document/__init__.py
  tests/unit/clients/python/test_request.py
Labels: area/core, size/S, area/testing, component/type

#3213 fix: license should be included in distribution
  MANIFEST.in
Labels: size/XS, area/setup

#3212 fix: fix listview insert, append
  jina/types/list.py
  tests/unit/types/document/test_document.py
  tests/unit/types/test_list_view.py
Labels: area/core, size/S, area/testing, component/type

#3216 fix: add jina-bot to the cla whitelist
  .github/workflows/cla.yml
Labels: area/housekeeping, area/cicd, size/XS

#3215 feat(hubio): modify fields of manifest produced by jina hub new
  jina/hubble/hubio.py
  jina/resources/executor-template/manifest.yml
Labels: area/core, size/S, component/resource

#3220 fix: fix graph plot
  jina/types/document/__init__.py
  tests/unit/types/document/test_graph_document.py
Labels: area/core, size/S, area/testing, component/type

#3224 refactor(except): rename Flow version except
  jina/excepts.py
  jina/helper.py
  jina/jaml/parsers/__init__.py
  jina/jaml/parsers/flow/v1.py
  jina/parsers/deprecated.py
  jina/parsers/helper.py
  tests/unit/flow/test_flow_yaml_parser.py
  tests/unit/parsers/test_warnings.py
Labels: size/M, area/core, area/helper, area/testing, component/jaml

#3226 fix(types): fix split swallow the category at float zero
  jina/types/arrays/search_ops.py
  tests/unit/types/arrays/test_documentarray.py
Labels: area/core, size/S, area/testing, component/type

#3228 docs: update the number of slack members
  README.md
Labels: size/XS

#3214 docs(readme): update links for tutorials and blogs
  README.md
Labels: size/XS

#3156 feat: add structuring executor repositories best practices
  .github/2.0/cookbooks/Executor.md
  jina/flow/base.py
  jina/importer.py
  jina/jaml/__init__.py
  jina/jaml/helper.py
  jina/parsers/peapods/runtimes/zed.py
  tests/integration/issues/github_1546/good1/crafter.yml
  tests/integration/issues/github_1546/good3/__init__.py
  tests/integration/issues/github_1546/good3/config.yml
  tests/integration/issues/github_1546/good3/helper.py
  tests/integration/issues/github_1546/good_new/crafter.yml
  tests/integration/issues/github_1546/good_new/executor/__init__.py
  tests/integration/issues/github_1546/good_new/executor/helper.py
  tests/integration/issues/github_1546/good_new/executor/my_crafter.py
  tests/integration/issues/github_1546/good_old/__init__.py
  tests/integration/issues/github_1546/good_old/crafter.yml
  tests/integration/issues/github_1546/good_old/helper.py
  tests/integration/issues/github_1546/test_pymodules_import.py
Labels: size/M, area/housekeeping, area/core, area/helper, area/testing, component/flow, component/jaml

#3222 feat(routing): add static routing table feature
  cli/autocomplete.py
  jina/flow/base.py
  jina/parsers/flow.py
  jina/parsers/peapods/base.py
  jina/peapods/grpc/__init__.py
  jina/peapods/pods/__init__.py
  jina/peapods/runtimes/grpc/__init__.py
  jina/peapods/runtimes/zmq/zed.py
  jina/peapods/zmq/__init__.py
  jina/proto/serializer.py
  jina/types/message/__init__.py
  jina/types/routing/table.py
  tests/unit/flow/test_flow_dynamic_routing.py
Labels: size/M, area/core, area/testing, area/network, component/peapod, component/flow, component/proto, component/type, area/cli

#3219 fix: no warning for metas in executor
  tests/unit/parsers/test_warnings.py
Labels: size/S, area/testing

#3235 perf: remove environment variable reading from init
  jina/types/ndarray/dense/numpy.py
Labels: area/core, size/XS, component/type

#3236 feat(daemon): add timeout to client
  daemon/clients/base.py
  daemon/clients/flows.py
  daemon/clients/peas.py
  daemon/clients/pods.py
  daemon/dockerize.py
  jina/peapods/runtimes/jinad/__init__.py
  tests/daemon/unit/clients/test_clients.py
Labels: area/core, size/S, area/testing, area/network, component/peapod, area/daemon

#3237 fix(helper): fix bad warning message on unknown cli
  cli/__init__.py
  jina/flow/base.py
  jina/helper.py
  jina/parsers/__init__.py
  jina/parsers/deprecated.py
  jina/parsers/helper.py
  tests/unit/parsers/test_warnings.py
  tests/unit/peapods/runtimes/gateway/http/test_app.py
  tests/unit/test_cli.py
Labels: size/M, area/core, area/helper, area/testing, component/flow, area/cli

#3238 refactor(helper): make progressbar more useful and modern
  jina/helloworld/chatbot/app.py
  jina/helloworld/fashion/helper.py
  jina/helloworld/multimodal/app.py
  jina/logging/profile.py
  tests/unit/test_progress_bar.py
Labels: size/M, area/core, area/testing, component/logging

#3239 perf(helloworld): optimize the performance of hello fashion
  cli/autocomplete.py
  jina/__init__.py
  jina/helloworld/fashion/app.py
  jina/helloworld/fashion/helper.py
  jina/logging/profile.py
  jina/parsers/helloworld.py
  jina/peapods/grpc/__init__.py
  scripts/latency-tracking/app.py
  tests/unit/test_progress_bar.py
Labels: area/core, area/helper, size/S, area/testing, area/network, component/logging, component/peapod, area/entrypoint, area/cli

#3246 fix(helper): fix small progressbar rendering problem
  jina/logging/profile.py
  tests/unit/test_progress_bar.py
Labels: area/core, size/S, area/testing, component/logging

#3244 fix(grpc): enable grpc runtime for http and websocket gateway
  jina/peapods/grpc/__init__.py
  jina/peapods/runtimes/gateway/http/app.py
  jina/peapods/runtimes/gateway/websocket/app.py
  jina/peapods/runtimes/grpc/__init__.py
  tests/unit/flow/test_flow_dynamic_routing.py
  tests/unit/peapods/runtimes/gateway/http/test_app.py
Labels: area/core, size/S, area/testing, area/network, component/peapod

#3255 feat(helper): add update desc & details for progressbar
  jina/logging/profile.py
  tests/unit/test_progress_bar.py
Labels: area/core, size/S, area/testing, component/logging

#3251 feat(daemon): support envvars
  .github/2.0/cookbooks/Daemon.md
  daemon/api/dependencies.py
  daemon/api/endpoints/flows.py
  daemon/api/endpoints/peas.py
  daemon/api/endpoints/pods.py
  daemon/clients/flows.py
  daemon/clients/peas.py
  daemon/dockerize.py
  daemon/helper.py
  daemon/stores/containers.py
  tests/daemon/unit/api/flow1.yml
  tests/daemon/unit/api/test_dependencies.py
  tests/distributed/test_workspaces/envvars_ws/executor.py
  tests/distributed/test_workspaces/envvars_ws/executor.yml
  tests/distributed/test_workspaces/envvars_ws/flow.yml
  tests/distributed/test_workspaces/test_envvars.py
  tests/distributed/test_workspaces/test_remote_workspaces.py
Labels: size/M, area/housekeeping, area/testing, area/daemon

#3248 feat(ci): enabled automated benchmarking
  .github/workflows/benchmark.yml
Labels: area/housekeeping, size/S, area/cicd

#3227 feat: make docs behavior consistent :boom:
  .github/2.0/cookbooks/Flow.md
  jina/clients/mixin.py
  jina/clients/request/__init__.py
  jina/clients/request/asyncio.py
  jina/helloworld/multimodal/flow-search.yml
  jina/peapods/pods/compound.py
  jina/peapods/runtimes/request_handlers/data_request_handler.py
  tests/integration/crud/flow.yml
  tests/integration/external_pod/test_external_pod.py
  tests/integration/inspect_pods_flow/test_inspect_pods_flow.py
  tests/integration/v2_api/test_func_routing.py
  tests/jinahub/flow.yml
Labels: size/M, area/housekeeping, area/core, area/testing, area/network, component/peapod, component/client

#3256 fix: read with args in flow.save_config
  jina/jaml/parsers/flow/v1.py
  tests/unit/flow/test_flow_yaml_parser.py
  tests/unit/flow/yaml/flow-gateway.yml
Labels: area/core, size/S, area/testing, component/jaml

#3262 fix(ci): fixed benchmark workflow syntax
  .github/workflows/benchmark.yml
Labels: area/housekeeping, size/S, area/cicd

#3263 fix: fix document update
  jina/types/document/__init__.py
  jina/types/struct.py
  tests/unit/types/document/test_document.py
Labels: area/core, size/S, area/testing, component/type

#3259 feat: add edges and nodes in batches
  .github/2.0/cookbooks/Document.md
  jina/helper.py
  jina/types/document/graph.py
  tests/integration/graph/test_graph_executor.py
  tests/unit/types/document/test_graph_document.py
Labels: area/housekeeping, size/L, area/core, area/helper, area/testing, component/type

#3268 fix(ci): fixed benchmark ci error
  .github/workflows/benchmark.yml
  jina/resources/extra-requirements.txt
Labels: area/housekeeping, area/core, size/S, area/cicd, component/resource

#3285 fix(ci): fixed benchmark ci
  .github/workflows/benchmark.yml
Labels: area/housekeeping, area/cicd, size/XS

#3174 feat: add conda recipe script
  conda/meta.yaml
  scripts/create-conda-recipe.py
Labels: size/M

#3264 fix(dam): warning truncate doc id
  jina/types/arrays/memmap.py
Labels: area/core, size/XS, component/type

#3274 perf: reuse loop to add edge features
  jina/types/document/graph.py
Labels: area/core, size/S, component/type

#3266 fix(daemon): manage ports for remote flows
  daemon/api/dependencies.py
  daemon/api/endpoints/flows.py
  daemon/api/endpoints/partial/flow.py
  daemon/models/__init__.py
  daemon/stores/containers.py
  daemon/stores/flows.py
  daemon/stores/partial.py
  jina/flow/base.py
  jina/jaml/parsers/flow/v1.py
  jina/parsers/peapods/runtimes/zed.py
  jina/peapods/peas/__init__.py
  jina/peapods/peas/helper.py
  jina/peapods/runtimes/container/__init__.py
  jina/peapods/runtimes/container/helper.py
  tests/daemon/unit/api/endpoints/partial/good_flow_dummy.yml
  tests/daemon/unit/api/endpoints/partial/test_flow.py
  tests/daemon/unit/api/flow2.yml
  tests/daemon/unit/api/flow3.yml
  tests/daemon/unit/api/test_dependencies.py
  tests/daemon/unit/stores/flow.yml
  tests/daemon/unit/stores/test_partialstore.py
  tests/distributed/test_topologies_docker/test_topologies_docker.py
  tests/distributed/test_topologies_docker/yamls/flow_gcg.yml
  tests/distributed/test_topologies_docker/yamls/flow_gclcg.yml
  tests/distributed/test_topologies_docker/yamls/flow_gclg.yml
  tests/distributed/test_topologies_docker/yamls/flow_glcg.yml
  tests/unit/flow/test_flow_yaml_parser.py
  tests/unit/peapods/runtimes/container/test_container_runtime.py
Labels: size/L, area/core, area/testing, area/network, component/peapod, component/flow, component/jaml, area/jinaD, area/daemon

#3296 Refactor don't resolve host
  jina/flow/base.py
Labels: area/core, size/S, component/flow

#3295 perf: add cache nodes
  jina/types/document/graph.py
Labels: size/M, area/core, component/type

#2939 feat: kubernetes mvp
  .github/workflows/ci.yml
  .gitignore
  cli/autocomplete.py
  extra-requirements.txt
  jina/enums.py
  jina/flow/base.py
  jina/hubble/hubio.py
  jina/parsers/__init__.py
  jina/parsers/flow.py
  jina/parsers/peapods/pod.py
  jina/peapods/pods/__init__.py
  jina/peapods/pods/factory.py
  jina/peapods/pods/k8s.py
  jina/peapods/pods/k8slib/__init__.py
  jina/peapods/pods/k8slib/kubernetes_deployment.py
  jina/peapods/pods/k8slib/kubernetes_tools.py
  jina/resources/extra-requirements.txt
  jina/resources/k8s/template/deployment-init.yml
  jina/resources/k8s/template/deployment.yml
  jina/resources/k8s/template/namespace.yml
  jina/resources/k8s/template/service.yml
  jina/types/routing/table.py
  tests/conftest.py
  tests/integration/hub_usage/test_hub_usage.py
  tests/k8s/__init__.py
  tests/k8s/conftest.py
  tests/k8s/dummy-dumper/.dockerignore
  tests/k8s/dummy-dumper/Dockerfile
  tests/k8s/dummy-dumper/dump.py
  tests/k8s/executor-merger/.dockerignore
  tests/k8s/executor-merger/Dockerfile
  tests/k8s/executor-merger/config.yml
  tests/k8s/executor-merger/exec_merger.py
  tests/k8s/test-executor/.dockerignore
  tests/k8s/test-executor/Dockerfile
  tests/k8s/test-executor/config.yml
  tests/k8s/test-executor/debug_executor.py
  tests/k8s/test_k8s.py
  tests/k8s/test_k8s.sh
  tests/unit/hubble/test_hubio.py
  tests/unit/peapods/pods/test_k8s_pod.py
  tests/unit/peapods/pods/test_pod_factory.py
  tests/unit/types/test_routing_graph.py
Labels: area/housekeeping, area/core, area/helper, area/cicd, area/testing, area/network, component/peapod, size/XL, component/resource, component/flow, area/setup, component/type, area/cli

#3304 fix(daemon): port mapping for compound pods
  daemon/api/dependencies.py
  daemon/api/endpoints/partial/flow.py
  daemon/files.py
  daemon/models/ports.py
  daemon/stores/containers.py
  daemon/stores/flows.py
  daemon/stores/partial.py
  tests/daemon/unit/api/endpoints/partial/test_flow.py
  tests/daemon/unit/api/test_dependencies.py
  tests/daemon/unit/models/test_ports.py
Labels: size/M, area/testing, area/daemon

#3311 fix(ci): fixed benchmark CI
  .github/workflows/benchmark.yml
  .github/workflows/cd.yml
Labels: area/housekeeping, size/S, area/cicd
