Repository jina-ai/serve, pull requests merged in 2023-03, with the labels that each got.

#5724 docs(clean-code): move menu item to developer reference
  docs/concepts/preliminaries/index.md
  docs/developer-reference/clean-code.md
  docs/index.md
Labels: area/docs, size/XS

#5723 refactor: health check ready after starting server
  jina/serve/runtimes/head/__init__.py
Labels: area/core, size/XS

#5725 feat: use grpc health check to wait for ready
  jina/orchestrate/pods/__init__.py
  jina/serve/networking/utils.py
  jina/serve/runtimes/asyncio.py
  tests/integration/runtimes/test_warmup.py
  tests/unit/orchestrate/deployments/test_deployments.py
Labels: size/M, area/core, size/S, area/testing

#5731 refactor: grpc logic to handler
  jina/serve/gateway.py
  jina/serve/instrumentation/__init__.py
  jina/serve/runtimes/asyncio.py
  jina/serve/runtimes/gateway/async_request_response_handling.py
  jina/serve/runtimes/gateway/grpc/gateway.py
  jina/serve/runtimes/gateway/http/app.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/gateway/websocket/app.py
  jina/serve/runtimes/head/__init__.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/runtimes/worker/__init__.py
  jina/serve/runtimes/worker/request_handling.py
  tests/integration/crud/flow.yml
  tests/integration/external_deployment/test_external_deployment.py
  tests/integration/gateway_streamer/test_gateway_streamer.py
  tests/integration/runtimes/test_network_failures.py
  tests/unit/serve/runtimes/head/test_head_runtime.py
  tests/unit/yaml/dummy_gateway_get_streamer.py
Labels: size/L, area/core, area/testing, size/XL

#5734 chore: change how to assign name
  jina_cli/api.py
Labels: size/XS, area/cli

#5740 docs: add readme link
  README.md
  docs/index.md
Labels: area/docs, size/XS

#5742 fix: adapt to docarray v2 update
  docs/concepts/executor/docarray-v2.md
  tests/integration/docarray_v2/test_v2.py
Labels: size/S, area/testing, area/docs

#5743 docs: remove docs qa
  docs/_templates/page.html
  docs/conf.py
Labels: size/S, area/docs

#5741 fix: composite gateway tracing support
  jina/serve/gateway.py
  jina/serve/runtimes/gateway/composite/gateway.py
  jina/serve/runtimes/gateway/request_handling.py
  tests/integration/instrumentation/test_flow_instrumentation.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_multiprotocol.py
Labels: size/M, area/core, size/S, area/testing

#5751 fix: revert grpc default options
  jina/serve/networking/utils.py
Labels: area/core, size/XS

#5736 fix: enable root logging always
  jina/logging/logger.py
  tests/unit/logging/test_logging.py
Labels: area/core, size/S, area/testing, component/logging, size/XS

#5760 docs: fix notebook colab link
  README.md
Labels: size/XS

#5762 cd: fix get openapi schemas
  scripts/get-openapi-schemas.py
Labels: size/XS

#5765 feat: introduce grpc_channel_options argument for providing custom grpc options for the channel
  docs/concepts/client/send-receive-data.md
  docs/concepts/flow/add-executors.md
  docs/concepts/flow/deployment-args.md
  docs/concepts/flow/executor-args.md
  docs/concepts/flow/gateway-args.md
  docs/concepts/gateway/index.md
  jina/clients/__init__.py
  jina/clients/base/grpc.py
  jina/jaml/parsers/gateway/legacy.py
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
  jina/parsers/__init__.py
  jina/parsers/orchestrate/runtimes/grpc_channel.py
  jina/parsers/orchestrate/runtimes/remote.py
  jina/parsers/orchestrate/runtimes/worker.py
  jina/serve/executors/__init__.py
  jina/serve/helper.py
  jina/serve/networking/__init__.py
  jina/serve/networking/connection_pool_map.py
  jina/serve/networking/connection_stub.py
  jina/serve/networking/replica_list.py
  jina/serve/networking/utils.py
  jina/serve/runtimes/asyncio.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/runtimes/helper.py
  jina/serve/runtimes/servers/__init__.py
  jina/serve/runtimes/servers/grpc.py
  jina_cli/autocomplete.py
  tests/integration/clients_extra_kwargs/test_clients_post_extra_kwargs.py
  tests/integration/external_deployment/test_external_deployment.py
  tests/integration/runtimes/test_runtimes.py
  tests/unit/clients/test_client_grpc_channel_options.py
  tests/unit/clients/test_helper.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_yaml_parser.py
  tests/unit/serve/runtimes/gateway/grpc/test_grpc_gateway_runtime.py
  tests/unit/serve/runtimes/head/test_head_runtime.py
  tests/unit/serve/runtimes/test_helper.py
  tests/unit/serve/runtimes/worker/test_worker_runtime.py
  tests/unit/test_yamlparser.py
  tests/unit/yaml/test-deployment.yml
Labels: size/L, area/core, area/testing, size/XL, area/docs, component/client, area/cli, component/jaml

#5750 feat: easier setup
  docs/concepts/flow/deployment-args.md
  docs/concepts/flow/executor-args.md
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
  jina/orchestrate/pods/__init__.py
  jina/parsers/orchestrate/runtimes/runtime.py
  jina/serve/consensus/jina_raft/fsm.go
  jina/serve/consensus/jina_raft/jinaraft.go
  jina/serve/consensus/jraft.go
  jina/serve/consensus/jraft.h
  jina/serve/consensus/run.go
  jina/serve/consensus/scripts/start_nodeA.sh
  jina/serve/executors/__init__.py
  jina/serve/helper.py
  jina_cli/autocomplete.py
  setup.py
Labels: size/M, area/core, area/docs, area/setup, area/cli

#5759 docs: jcloud docs revamp for instance
  docs/concepts/jcloud/configuration.md
  docs/concepts/jcloud/index.md
  docs/jina-ai-cloud/index.md
Labels: size/M, area/docs

#5774 fix: fix docarray v2 issue
  jina/_docarray.py
  tests/integration/docarray_v2/test_v2.py
Labels: area/core, area/helper, size/S, area/testing

#5775 test: upgrade to otel 1.17
  tests/unit/serve/instrumentation/conftest.py
  tests/unit/serve/instrumentation/test_gateway_metric_labels.py
Labels: size/S, area/testing

#5771 feat: allow option to disable thread lock
  docs/concepts/flow/deployment-args.md
  docs/concepts/flow/executor-args.md
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
  jina/parsers/orchestrate/runtimes/worker.py
  jina/serve/executors/__init__.py
  jina_cli/autocomplete.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_except.py
Labels: area/core, size/S, area/testing, area/docs, area/cli

#5779 chore: hide survey if env is set
  jina/orchestrate/flow/base.py
Labels: area/core, size/S, size/XS

#5780 chore: add backwards compatibility
  jina/serve/runtimes/servers/composite.py
Labels: area/core, size/XS
