Repository jina-ai/serve, pull requests merged in 2023-11, with the labels that each got.

#6102 fix(sagemaker): read csv with escaped chars
  jina/serve/runtimes/worker/http_sagemaker_app.py
  jina_cli/autocomplete.py
  tests/integration/docarray_v2/sagemaker/SampleExecutor/executor.py
  tests/integration/docarray_v2/sagemaker/test_sagemaker.py
  tests/integration/docarray_v2/sagemaker/valid_input_1.csv
  tests/integration/docarray_v2/sagemaker/valid_input_2.csv
Labels: size/M, area/core, size/S, area/testing, area/cli

#6104 ci: enable prerelease
  .github/workflows/cd.yml
Labels: area/housekeeping, size/S, area/cicd

#6105 ci: disable prerelease
  .github/workflows/cd.yml
Labels: area/housekeeping, size/S, area/cicd

#6106 ci: fix issues with CD and K8s tests
  .github/workflows/cd.yml
Labels: area/housekeeping, size/S, area/cicd

#6108 refactor: call extend rest interface in worker
  jina/serve/runtimes/worker/request_handling.py
  tests/conftest.py
Labels: area/core, area/testing, size/XS

#6113 chore: update version to 3.23.0
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#6114 refactor: remove warmup
  jina/serve/networking/__init__.py
  jina/serve/networking/replica_list.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/runtimes/servers/__init__.py
  tests/integration/instrumentation/test_flow_instrumentation.py
  tests/integration/runtimes/test_warmup.py
  tests/unit/serve/networking/test_replica_list.py
Labels: size/M, area/core, area/testing

#6115 refactor: use asyncio Events over threading Events
  jina/orchestrate/pods/container.py
  jina/serve/networking/__init__.py
  jina/serve/runtimes/asyncio.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/runtimes/servers/__init__.py
Labels: size/M, area/core, size/S

#6116 refactor: fix run stateful in docker
  jina/serve/executors/run.py
Labels: area/core, size/S, size/XS
