Repository jina-ai/serve, pull requests merged in 2023-06, with the labels that each got.

#5900 test: add test with shaped ndarray
  jina_cli/autocomplete.py
  tests/integration/docarray_v2/test_v2.py
Labels: size/S, area/testing, area/cli

#5904 fix: fix isse in head missmatch endpoint
  jina/serve/runtimes/head/request_handling.py
  tests/integration/docarray_v2/test_v2.py
Labels: area/core, size/S, area/testing

#5906 fix: ensure closing Executor at shutdown in HTTP Deployment
  jina/orchestrate/deployments/__init__.py
  jina/serve/runtimes/worker/request_handling.py
  tests/integration/docarray_v2/test_v2.py
Labels: area/core, size/S, area/testing

#5909 docs: fix links in docs
  docs/jina-ai-cloud/index.md
Labels: area/docs, size/XS

#5908 fix: fix tags doc schema
  jina/serve/runtimes/helper.py
  tests/integration/docarray_v2/test_v2.py
Labels: area/core, size/S, area/testing

#5910 fix(readme): image urls
  .github/images/mona-lisa.png
  README.md
Labels: area/housekeeping, size/S

#5911 ci: fix debianx Dockerfile
  Dockerfiles/debianx.Dockerfile
Labels: area/docker, size/XS

#5517 chore: test on python 3.8 in CI/CD and use python version matrix for import test
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  tests/integration/issues/github_5141/test_invalid_input_raises_exception.py
Labels: size/M, area/housekeeping, size/S, area/cicd, area/testing

#5899 feat: streaming with HTTP SSE for deployment
  docs/concepts/serving/executor/add-endpoints.md
  docs/docarray-v2.md
  jina/clients/base/__init__.py
  jina/clients/base/helper.py
  jina/clients/base/http.py
  jina/clients/mixin.py
  jina/helper.py
  jina/serve/executors/__init__.py
  jina/serve/executors/decorators.py
  jina/serve/networking/sse.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/servers/http.py
  jina/serve/runtimes/worker/http_fastapi_app.py
  jina/serve/runtimes/worker/request_handling.py
  jina/types/request/data.py
  tests/integration/deployment_http_composite/test_deployment_http_composite.py
  tests/integration/deployment_http_composite/test_deployment_http_composite_docarray_v2.py
  tests/integration/docarray_v2/test_streaming.py
  tests/integration/streaming/test_streaming.py
  tests/unit/test_helper.py
Labels: size/L, area/core, area/helper, area/testing, size/XL, area/docs, component/client, component/type

#5914 fix: consider env from secrets in gateway
  jina/orchestrate/deployments/config/k8s.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
Labels: area/core, area/testing, size/XS

#5918 chore: remove bad tests
  tests/unit/clients/python/test_request.py
Labels: size/S, area/testing

#5917 chore: change reported name
  jina/serve/runtimes/asyncio.py
Labels: area/core, size/XS

#5915 fix: fix reloading Executor when is loaded from `config.yml`
  jina/serve/runtimes/worker/request_handling.py
  tests/integration/hot_reload/exec4/__init__.py
  tests/integration/hot_reload/exec4/config.yml
  tests/integration/hot_reload/exec4/my_executor4.py
  tests/integration/hot_reload/my_executor_4_new.py
  tests/integration/hot_reload/test_hot_reload.py
Labels: area/core, size/S, area/testing, size/XS

#5919 chore: head and gateway start later
  jina/orchestrate/deployments/__init__.py
Labels: area/core, size/S

#5905 fix: detect Tensor vs List of float when creating dynamic Pydantic model
  jina/serve/runtimes/helper.py
  tests/integration/docarray_v2/test_v2.py
  tests/unit/serve/runtimes/test_helper.py
Labels: area/core, size/S, area/testing

#5920 chore: add logs helping to investigate
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/pods/__init__.py
  jina/orchestrate/pods/container.py
  jina/serve/executors/run.py
  jina/serve/networking/__init__.py
  jina/serve/runtimes/asyncio.py
  jina/serve/runtimes/gateway/graph/topology_graph.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/runtimes/servers/__init__.py
  jina/serve/runtimes/servers/composite.py
  jina/serve/runtimes/servers/grpc.py
  jina/serve/runtimes/servers/http.py
  jina/serve/runtimes/servers/load_balancer.py
  jina/serve/runtimes/servers/websocket.py
  jina/serve/runtimes/worker/request_handling.py
  jina/serve/stream/__init__.py
  jina_cli/api.py
  tests/integration/docarray_v2/test_v2.py
  tests/integration/dynamic_batching/test_dynamic_batching.py
  tests/integration/network_failures/test_network_failures.py
  tests/unit/clients/python/test_request.py
  tests/unit/orchestrate/pods/test_pod.py
Labels: size/M, area/core, area/testing, area/cli

#5927 chore: remove daemon
  jina/orchestrate/deployments/__init__.py
Labels: area/core, size/XS

#5925 chore: remove AddVoterError unused object
  jina/serve/consensus/jraft.go
Labels: area/core, size/S

#5926 chore: upgrade version to 3.18.0
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#5930 fix(readme): text not tags in code snippets
  README.md
Labels: size/XS

#5934 fix: fix plot of Flows
  jina/orchestrate/flow/base.py
Labels: area/core, size/XS

#5935 feat: use dynamic gateway hubble image
  jina/constants.py
  jina/orchestrate/deployments/config/docker_compose.py
  jina/orchestrate/deployments/config/helper.py
  jina/orchestrate/deployments/config/k8s.py
  jina/resources/base-gateway/Dockerfile
  jina/resources/base-gateway/README.md
  jina/resources/base-gateway/config.yml
  jina/resources/base-gateway/gateway.py
  tests/conftest.py
  tests/integration/clients_extra_kwargs/test_clients_post_extra_kwargs.py
  tests/k8s/conftest.py
  tests/k8s_otel/conftest.py
  tests/unit/orchestrate/deployments/config/test_docker_compose_pod_config.py
  tests/unit/orchestrate/deployments/config/test_k8s_deployment_config.py
Labels: size/M, size/L, area/core, area/helper, size/S, area/testing, component/resource

#5940 chore: change urllib minimal requirement
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: area/core, size/XS, component/resource, area/setup

#5929 chore: unpin docarray version and adapt CI/CD
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfiles/test-pip.Dockerfile
  extra-requirements.txt
  jina/resources/extra-requirements.txt
  jina/serve/runtimes/gateway/graph/topology_graph.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/websocket_fastapi_app.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/stream/__init__.py
  tests/integration/docarray_v2/test_v2.py
  tests/jinahub/Dockerfile
  tests/jinahub/app.py
  tests/jinahub/test_integration.sh
  tests/k8s/test_k8s_flow.py
Labels: size/M, area/housekeeping, area/docker, area/core, size/S, area/cicd, area/testing, component/resource, area/setup

#5942 docs: dummy commit to pre release
  CONTRIBUTING.md
Labels: size/XS

#5943 ci: fix update schema in CD
  .github/workflows/cd.yml
  jina/serve/stream/__init__.py
Labels: area/housekeeping, area/core, size/S, area/cicd, size/XS
