Repository jina-ai/serve, pull requests merged in 2023-09, with the labels that each got.

#6037 fix: fix install issue
  .github/workflows/ci.yml
  extra-requirements.txt
  jina/resources/extra-requirements.txt
  tests/k8s/conftest.py
  tests/k8s/test_k8s_failures.py
  tests/k8s/test_k8s_flow.py
Labels: area/housekeeping, area/core, size/S, area/cicd, area/testing, size/XS, component/resource, area/setup

#6027 feat: add return_type parameter to gateway streamer methods to allow …
  docs/concepts/serving/gateway/customization.md
  jina/clients/base/http.py
  jina/clients/base/unary_rpc.py
  jina/clients/base/websocket.py
  jina/serve/runtimes/gateway/async_request_response_handling.py
  jina/serve/runtimes/gateway/graph/topology_graph.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/stream/__init__.py
  tests/integration/docarray_v2/test_v2.py
  tests/unit/serve/stream/test_stream.py
Labels: size/M, size/L, area/core, area/testing, area/docs, component/client

#6047 fix: remove sandbox
  .github/workflows/label-pr.yml
  docs/cloud-nativeness/kubernetes.md
  docs/concepts/orchestration/add-executors.md
  docs/concepts/serving/executor/hub/hub-portal.md
  docs/concepts/serving/executor/hub/index.md
  docs/concepts/serving/executor/hub/sandbox.md
  docs/redirects.txt
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
  tests/integration/issues/github_4488/test_deployment_protocol.py
  tests/integration/sandbox/test_sandbox.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_to_docker_compose_yaml.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
Labels: size/M, area/housekeeping, area/core, area/cicd, area/testing, area/docs

#6050 ci: enable prerelease
  .github/workflows/cd.yml
Labels: area/housekeeping, size/S, area/cicd

#6032 fix: document casting in flow gateway
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  tests/integration/docarray_v2/test_v2.py
Labels: size/M, area/core, area/testing

#6051 fix: fix weird host assignemnt in k8s yaml
  jina/orchestrate/deployments/config/k8s.py
  jina/orchestrate/deployments/config/k8slib/kubernetes_deployment.py
Labels: area/core, size/S

#6053 chore: make message more explicit to see error
  jina/serve/runtimes/gateway/graph/topology_graph.py
Labels: area/core, size/S, size/XS

#6056 fix(consensus): free more cstrings
  jina/serve/consensus/run.go
Labels: area/core, size/XS

#6057 fix: fix topology schema validation
  jina/serve/runtimes/gateway/graph/topology_graph.py
  tests/integration/docarray_v2/test_v2.py
Labels: size/M, area/core, area/testing

#6059 chore: update to version 3.21.0
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#6061 ci: remove hub integration test
  .github/workflows/force-release.yml
Labels: area/housekeeping, size/S, area/cicd

#6055 feat(sagemaker): support batch-transform
  jina/orchestrate/deployments/__init__.py
  jina/serve/runtimes/worker/http_sagemaker_app.py
  tests/integration/docarray_v2/sagemaker/Dockerfile
  tests/integration/docarray_v2/sagemaker/SampleExecutor/executor.py
  tests/integration/docarray_v2/sagemaker/invalid_input.csv
  tests/integration/docarray_v2/sagemaker/test_sagemaker.py
  tests/integration/docarray_v2/sagemaker/valid_input.csv
  tests/integration/docarray_v2/test_parameters_as_pydantic.py
Labels: size/M, area/core, area/testing

#6062 fix: fix issue with same doc type in spawned processes
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  jina/serve/stream/__init__.py
  tests/integration/docarray_v2/docker/__init__.py
  tests/integration/docarray_v2/docker/executor1/Dockerfile
  tests/integration/docarray_v2/docker/executor1/__init__.py
  tests/integration/docarray_v2/docker/executor1/config.yml
  tests/integration/docarray_v2/docker/executor1/executor.py
  tests/integration/docarray_v2/docker/executor2/Dockerfile
  tests/integration/docarray_v2/docker/executor2/__init__.py
  tests/integration/docarray_v2/docker/executor2/config.yml
  tests/integration/docarray_v2/docker/executor2/executor.py
  tests/integration/docarray_v2/docker/test_with_docker.py
Labels: size/M, area/housekeeping, area/core, size/S, area/cicd, area/testing

#6065 docs: fix line explaining dynamic batching in yaml
  docs/concepts/serving/executor/dynamic-batching.md
Labels: area/docs, size/XS
