Repository jina-ai/serve, pull requests merged in 2023-05, with the labels that each got.

#5844 chore: fix link to survey
  jina/orchestrate/flow/base.py
Labels: area/core, size/XS

#5846 chore: fix links in README
  README.md
Labels: size/XS

#5848 chore: pin urllib
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: area/core, size/XS, component/resource, area/setup

#5849 chore: bump jina version
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#5850 test: fix test private exec
  tests/unit/orchestrate/deployments/test_deployments.py
  tests/unit/serve/executors/test_executor.py
Labels: area/testing, size/XS

#5845 ci integrate wheels building
  .github/workflows/force-release.yml
  .github/workflows/stateful-build-wheels.yml
  scripts/release.sh
  scripts/update-version.sh
Labels: size/M, area/housekeeping, area/cicd

#5852 chore: remove non-existing property
  jina/orchestrate/deployments/__init__.py
Labels: area/core, size/XS

#5853 fix: return awaited text in content type
  jina/clients/base/helper.py
Labels: area/core, size/XS, component/client

#5854 fix: fix link to docs for Http
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
Labels: area/core, size/S

#5855 chore: remove useless print
  jina/orchestrate/flow/base.py
Labels: area/core, size/XS

#5863 ci: try to fix CD
  .github/workflows/cd.yml
Labels: area/housekeeping, area/cicd, size/XS

#5867 ci: fix cd
  .github/workflows/cd.yml
Labels: area/housekeeping, size/S, area/cicd

#5869 ci: fix fetch depth to get right num commits
  .github/workflows/cd.yml
Labels: area/housekeeping, area/cicd, size/XS

#5870 ci: try to fetch inside the step
  .github/workflows/cd.yml
Labels: area/housekeeping, area/cicd, size/XS

#5871 ci: fix prerelease
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/force-release.yml
  docs/concepts/orchestration/scale-out.md
  setup.py
Labels: area/housekeeping, size/S, area/cicd, area/docs, area/setup

#5875 ci: try to fix build wheels on mac archs
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .github/workflows/force-release.yml
Labels: area/housekeeping, size/S, area/cicd

#5877 chore: change docstring of write decorator
  docs/concepts/orchestration/scale-out.md
  jina/orchestrate/deployments/__init__.py
  jina/serve/executors/decorators.py
Labels: area/core, size/S, area/docs

#5878 chore: bump jina version
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#5879 chore: hide codecov
  README.md
Labels: size/XS

#5880 chore: release 316 branch to bypass notes error
  docs/_versions.json
  jina/__init__.py
Labels: area/core, area/helper, area/docs, size/XS, area/entrypoint

#5883 fix: fix link to docs and redocs
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
Labels: area/core, size/S

#5885 fix: fix disallow list of arguments
  jina/orchestrate/flow/base.py
  jina_cli/autocomplete.py
  tests/integration/flow_dry_run/test_flow_dry_run.py
Labels: area/core, size/S, area/testing, size/XS, area/cli

#5887 docs: fix links in yaml specs
  docs/yaml-spec.md
Labels: area/docs, size/XS

#5888 fix: remove outdated protobuf that caused notebook crash
  .github/getting-started/notebook.ipynb
Labels: area/housekeeping, size/XS

#5891 chore: remove aiostream dependency
  extra-requirements.txt
  jina/clients/request/asyncio.py
  jina/resources/extra-requirements.txt
  jina/serve/stream/__init__.py
Labels: area/core, size/S, component/resource, area/setup, component/client

#5892 docs: add docs for jc logs
  docs/concepts/jcloud/img/executor_logs.png
  docs/concepts/jcloud/img/gateway_logs.png
  docs/concepts/jcloud/index.md
Labels: size/S, area/docs

#5861 feat: Flow compatible with docarray v2
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  docs/docarray-v2.md
  jina/clients/request/helper.py
  jina/serve/consensus/run.go
  jina/serve/networking/__init__.py
  jina/serve/networking/replica_list.py
  jina/serve/runtimes/gateway/async_request_response_handling.py
  jina/serve/runtimes/gateway/graph/topology_graph.py
  jina/serve/runtimes/gateway/health_model.py
  jina/serve/runtimes/gateway/http_fastapi_app.py
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  jina/serve/runtimes/gateway/models.py
  jina/serve/runtimes/gateway/request_handling.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/gateway/websocket_fastapi_app.py
  jina/serve/runtimes/head/request_handling.py
  jina/serve/runtimes/helper.py
  jina/serve/runtimes/servers/grpc.py
  jina/serve/runtimes/servers/http.py
  jina/serve/runtimes/servers/websocket.py
  jina/serve/runtimes/worker/http_fastapi_app.py
  jina/serve/runtimes/worker/request_handling.py
  jina/serve/stream/__init__.py
  tests/integration/deployment_http_composite/test_deployment_http_composite.py
  tests/integration/deployment_http_composite/test_deployment_http_composite_docarray_v2.py
  tests/integration/docarray_v2/test_v2.py
  tests/unit/serve/runtimes/gateway/graph/test_topology_graph.py
  tests/unit/serve/runtimes/test_helper.py
Labels: size/M, area/housekeeping, size/L, area/core, area/cicd, area/testing, size/XL, area/docs, component/client

#5897 fix: fix instantiate of Executor with `write` decorator
  jina/serve/executors/decorators.py
  tests/unit/serve/executors/test_executor.py
Labels: area/core, size/S, area/testing

#5896 chore: try fix setting start method
  jina/__init__.py
  jina/helper.py
Labels: area/core, area/helper, size/S, area/entrypoint

#5901 chore: remove annoying message for debug
  jina/serve/consensus/jina_raft/rpc.go
  jina/serve/networking/__init__.py
Labels: area/core, size/XS
