Repository jina-ai/serve, pull requests merged in 2023-07, with the labels that each got.

#5946 ci: limit pydantic version
  extra-requirements.txt
  jina/resources/extra-requirements.txt
Labels: area/core, size/XS, component/resource, area/setup

#5947 fix: fix is generator detection
  jina/helper.py
  tests/unit/test_helper.py
Labels: area/core, area/helper, size/S, area/testing

#5949 fix: apply return_type also when return responses
  jina/clients/mixin.py
Labels: area/core, size/XS, component/client

#5952 feat: add ImagePullSecrets argument
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/deployments/config/helper.py
  jina/orchestrate/deployments/config/k8s.py
  jina/orchestrate/deployments/config/k8slib/kubernetes_deployment.py
  jina/orchestrate/deployments/config/k8slib/kubernetes_tools.py
  jina/orchestrate/flow/base.py
  jina/parsers/orchestrate/pod.py
  jina/resources/base-gateway/config.yml
  jina/serve/executors/__init__.py
  jina_cli/autocomplete.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
Labels: area/core, size/S, area/testing, component/resource, area/cli

#5956 fix: fix validation with default endpoint
  jina/serve/runtimes/gateway/graph/topology_graph.py
  tests/integration/docarray_v2/test_v2.py
Labels: area/core, size/S, area/testing

#5937 chore: upgrade jina version
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#5962 fix: fail fast when no valid schemas
  jina/orchestrate/flow/base.py
  jina/serve/executors/__init__.py
  jina/serve/runtimes/asyncio.py
  tests/integration/docarray_v2/test_v2.py
  tests/integration/docarray_v2/wrong_schema_executor.py
Labels: area/core, size/S, area/testing

#5965 fix: monitoring validation error
  jina/serve/runtimes/worker/request_handling.py
  tests/integration/docarray_v2/test_v2.py
Labels: size/M, area/core, area/testing, size/XS

#5961 fix: properly handle mulitprotocol Deployment to Kubernetes
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/deployments/config/k8s.py
  jina/orchestrate/deployments/config/k8slib/kubernetes_deployment.py
  jina/serve/networking/__init__.py
  tests/k8s/test_k8s_deployment.py
  tests/k8s/test_k8s_flow.py
  tests/unit/orchestrate/deployments/config/test_k8s_deployment_config.py
  tests/unit/orchestrate/deployments/test_deployments.py
  tests/unit/orchestrate/flow/flow-construct/test_flow_to_k8s_yaml.py
  tests/unit/serve/executors/test_executor.py
Labels: size/M, area/housekeeping, area/core, size/S, area/cicd, area/testing, size/XS

#5970 fix: dynamic batching with new docarray
  jina/serve/runtimes/worker/batch_queue.py
  jina/serve/runtimes/worker/request_handling.py
  tests/integration/docarray_v2/test_v2.py
  tests/unit/serve/dynamic_batching/test_batch_queue.py
Labels: area/core, size/S, area/testing

#5972 fix: unset http proxy
  jina/serve/runtimes/asyncio.py
  jina/serve/runtimes/servers/grpc.py
Labels: area/core, size/S, size/XS

#5975 ci: bump up python version to 3.8
  .github/workflows/force-release.yml
Labels: area/housekeeping, area/cicd, size/XS

#5957 docs: add docs for jcloud horizontal pod autoscale
  docs/concepts/jcloud/configuration.md
Labels: size/S, area/docs

#5977 fix: fix example shown in SwaggerUI for Flow with HTTP
  jina/helper.py
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
Labels: area/core, area/helper, size/XS

#5978 chore: refactor CompositeServer for better extendability
  jina/serve/runtimes/servers/__init__.py
  jina/serve/runtimes/servers/composite.py
Labels: area/core, size/S

#5921 feat: Document by Document streaming for gRPC protocol
  .github/workflows/ci.yml
  Dockerfiles/protogen-3.21.Dockerfile
  Dockerfiles/protogen.Dockerfile
  docs/concepts/serving/executor/add-endpoints.md
  jina/clients/base/grpc.py
  jina/clients/base/http.py
  jina/clients/base/stream_rpc.py
  jina/clients/base/unary_rpc.py
  jina/clients/base/websocket.py
  jina/clients/helper.py
  jina/proto/docarray_v1/docarray.proto
  jina/proto/docarray_v1/jina.proto
  jina/proto/docarray_v1/pb/jina_pb2.py
  jina/proto/docarray_v1/pb/jina_pb2_grpc.py
  jina/proto/docarray_v1/pb2/jina_pb2.py
  jina/proto/docarray_v1/pb2/jina_pb2_grpc.py
  jina/proto/docarray_v2/docarray.proto
  jina/proto/docarray_v2/jina.proto
  jina/proto/docarray_v2/pb/jina_pb2.py
  jina/proto/docarray_v2/pb/jina_pb2_grpc.py
  jina/proto/docarray_v2/pb2/jina_pb2.py
  jina/proto/docarray_v2/pb2/jina_pb2_grpc.py
  jina/proto/serializer.py
  jina/serve/consensus/jina-go-proto/jina.pb.go
  jina/serve/consensus/jina-go-proto/jina_grpc.pb.go
  jina/serve/consensus/jina.proto
  jina/serve/executors/__init__.py
  jina/serve/executors/decorators.py
  jina/serve/runtimes/servers/grpc.py
  jina/serve/runtimes/worker/request_handling.py
  jina/types/request/data.py
  tests/integration/docarray_v2/test_streaming.py
  tests/integration/docarray_v2/test_v2.py
  tests/integration/streaming/test_streaming.py
Labels: area/housekeeping, area/docker, size/L, area/core, size/S, area/cicd, area/testing, area/network, size/XL, area/docs, component/client, component/proto, component/type

#5979 chore: remove useless import
  jina/serve/runtimes/servers/grpc.py
Labels: area/core, size/XS

#5981 fix: fix streaming validation error message
  jina/serve/runtimes/worker/request_handling.py
Labels: area/core, size/XS

#5983 chore: small refactor
  jina/serve/runtimes/servers/composite.py
Labels: area/core, size/S

#5980 docs: streaming documentation
  README.md
  docs/concepts/serving/executor/add-endpoints.md
  docs/index.md
  docs/tutorials/llm-serve.md
Labels: size/M, area/docs, size/XS

#5985 docs: add kubernetes hint to port ignored
  docs/cloud-nativeness/k8s.md
  docs/cloud-nativeness/kubernetes.md
  docs/concepts/orchestration/deployment.md
  docs/concepts/orchestration/flow.md
  docs/tutorials/index.md
Labels: size/M, area/docs

#5987 docs: remove include gateway arg
  README.md
Labels: size/XS

#5988 feat: support streaming in Flow with one Executor
  jina/clients/base/helper.py
  jina/clients/base/http.py
  jina/serve/runtimes/gateway/graph/topology_graph.py
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  jina/serve/runtimes/gateway/streamer.py
  jina/serve/runtimes/worker/http_fastapi_app.py
  jina/serve/stream/__init__.py
  jina/types/request/data.py
  tests/integration/docarray_v2/test_streaming.py
Labels: size/M, area/core, area/testing, component/client, component/type

#5948 docs: add docs for secrets & jobs
  docs/concepts/jcloud/img/get_job.png
  docs/concepts/jcloud/img/get_secret.png
  docs/concepts/jcloud/img/job_logs.png
  docs/concepts/jcloud/img/list_jobs.png
  docs/concepts/jcloud/img/list_secrets.png
  docs/concepts/jcloud/index.md
Labels: size/M, area/docs

#5989 fix: respect req-id from client
  jina/serve/runtimes/worker/request_handling.py
Labels: area/core, size/XS

#5990 docs: add note about flow with one executor supported
  docs/concepts/serving/executor/add-endpoints.md
Labels: area/docs, size/XS

#5992 feat: expose richer OpenAPI.json from Flow with HTTP
  jina/serve/runtimes/helper.py
  tests/integration/docarray_v2/test_v2.py
Labels: area/core, size/S, area/testing

#5968 fix: ignore warnings from google
  jina/__init__.py
Labels: area/core, area/helper, size/S, area/entrypoint

#5993 fix: small fix OpenAPI.json with description
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  jina/serve/runtimes/helper.py
  jina/serve/runtimes/worker/http_fastapi_app.py
  tests/integration/docarray_v2/test_v2.py
Labels: size/M, area/housekeeping, area/core, size/S, area/cicd, area/testing

#5997 chore: fix uvicorn version to avoid breaking test
  extra-requirements.txt
Labels: size/XS, area/setup

#5995 fix: show examples in SwaggerUI
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  jina/serve/runtimes/worker/http_fastapi_app.py
Labels: area/core, size/S
