Repository jina-ai/serve, pull requests merged in 2024-04, with the labels that each got.

#6159 feat: executor to azure custom container
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  jina/enums.py
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
  jina/serve/executors/__init__.py
  jina/serve/runtimes/asyncio.py
  jina/serve/runtimes/servers/http.py
  jina/serve/runtimes/worker/http_csp_app.py
  jina/serve/runtimes/worker/request_handling.py
  tests/integration/docarray_v2/csp/Dockerfile
  tests/integration/docarray_v2/csp/SampleColbertExecutor/README.md
  tests/integration/docarray_v2/csp/SampleColbertExecutor/config.yml
  tests/integration/docarray_v2/csp/SampleColbertExecutor/executor.py
  tests/integration/docarray_v2/csp/SampleColbertExecutor/requirements.txt
  tests/integration/docarray_v2/csp/SampleExecutor/README.md
  tests/integration/docarray_v2/csp/SampleExecutor/config.yml
  tests/integration/docarray_v2/csp/SampleExecutor/executor.py
  tests/integration/docarray_v2/csp/SampleExecutor/requirements.txt
  tests/integration/docarray_v2/csp/SampleRerankerExecutor/README.md
  tests/integration/docarray_v2/csp/SampleRerankerExecutor/config.yml
  tests/integration/docarray_v2/csp/SampleRerankerExecutor/executor.py
  tests/integration/docarray_v2/csp/SampleRerankerExecutor/requirements.txt
  tests/integration/docarray_v2/csp/__init__.py
  tests/integration/docarray_v2/csp/invalid_input.csv
  tests/integration/docarray_v2/csp/test_azure.py
  tests/integration/docarray_v2/csp/test_sagemaker_colbert.py
  tests/integration/docarray_v2/csp/test_sagemaker_embedding.py
  tests/integration/docarray_v2/csp/test_sagemaker_reranking.py
  tests/integration/docarray_v2/csp/valid_input_1.csv
  tests/integration/docarray_v2/csp/valid_input_2.csv
  tests/integration/docarray_v2/csp/valid_reranker_input.csv
Labels: size/M, area/housekeeping, area/core, area/helper, area/cicd, area/testing

#6160 chore: upgrade ver
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint

#6162 chore: update black dependency
  extra-requirements.txt
  jina/clients/__init__.py
  jina/orchestrate/flow/base.py
  jina/serve/executors/__init__.py
Labels: area/core, size/S, size/XS, area/setup, component/client

#6163 fix: fix usage of input model
  jina/serve/runtimes/worker/http_csp_app.py
Labels: area/core, size/XS
