Repository jina-ai/serve, pull requests merged in 2024-03, with the labels that each got.

#6149 feat: support provider endpoint in jina executor
  jina/orchestrate/deployments/__init__.py
  jina/orchestrate/flow/base.py
  jina/parsers/orchestrate/pod.py
  jina/serve/executors/__init__.py
  jina/serve/runtimes/worker/request_handling.py
  jina_cli/autocomplete.py
  tests/integration/docarray_v2/sagemaker/SampleColbertExecutor/README.md
  tests/integration/docarray_v2/sagemaker/SampleColbertExecutor/config.yml
  tests/integration/docarray_v2/sagemaker/SampleColbertExecutor/executor.py
  tests/integration/docarray_v2/sagemaker/SampleColbertExecutor/requirements.txt
  tests/integration/docarray_v2/sagemaker/test_colbert.py
Labels: size/M, area/core, size/S, area/testing, area/cli

#6155 fix: fix issue with float
  jina/serve/runtimes/helper.py
  tests/unit/serve/runtimes/test_helper.py
Labels: area/core, size/S, area/testing, size/XS

#6152 refactor: keep only sagemaker endpoint
  jina/serve/executors/__init__.py
  jina/serve/runtimes/gateway/http_fastapi_app_docarrayv2.py
  jina/serve/runtimes/worker/http_fastapi_app.py
  jina/serve/runtimes/worker/http_sagemaker_app.py
  tests/integration/docarray_v2/test_parameters_as_pydantic.py
Labels: size/M, area/core, size/S, area/testing
