Repository jina-ai/serve, pull requests merged in 2024-11, with the labels that each got.

#6216 feat: fix batch handling in sagemaker for clip
  jina/orchestrate/flow/base.py
  jina/serve/executors/__init__.py
  jina/serve/runtimes/worker/http_csp_app.py
  tests/integration/docarray_v2/csp/SampleClipExecutor/executor.py
  tests/integration/docarray_v2/csp/valid_clip_input.csv
Labels: area/core, size/S, area/testing

#6217 fix: test hubapp hubpods fix
  tests/jinahub/test_integration.sh
Labels: area/testing, size/XS

#6218 fix: fix req handling sagemaker
  jina/serve/runtimes/worker/request_handling.py
Labels: area/core, size/S

#6198 ci: unblock grpcio version
  Dockerfiles/pip.Dockerfile
  Dockerfiles/test-pip.Dockerfile
  extra-requirements.txt
  tests/docker_compose/conftest.py
  tests/docker_compose/test_flow_docker_compose.py
  tests/integration/deployment_http_composite/test_deployment_http_composite_docarray_v2.py
  tests/integration/docarray_v2/test_v2.py
  tests/integration/network_failures/test_network_failures.py
  tests/k8s_otel/test_k8s_instrumentation.py
  tests/unit/serve/instrumentation/conftest.py
  tests/unit/serve/instrumentation/test_gateway_metric_labels.py
  tests/unit/serve/instrumentation/test_instrumentation.py
Labels: size/M, area/docker, size/L, size/S, area/testing, size/XS, area/setup

#6219 chore: update version
  jina/__init__.py
Labels: area/core, area/helper, size/XS, area/entrypoint
